# tsconfig.json

In [139]:
from bs4 import BeautifulSoup, NavigableString
from os.path import join
import re
import pandas as pd
from IPython.display import display, HTML

REPO_ABSPATH = "/utkusarioglu-com/workshops/backtesting-workshop"
assets_abspath = join(REPO_ABSPATH, "assets/typescript")
artifacts_abspath = join(REPO_ABSPATH, "artifacts/typescript")
source_abspath = join(assets_abspath, "tsconfig_json.html")
target_abspath = join(artifacts_abspath, "tsconfig_json.csv")
options = ["display.max_rows", None]

In [13]:
html = open(source_abspath, "r").read()
html

'<div>\n  <div class="tsconfig raised main-content-block markdown">\n    <article id="Top Level">\n      <h3 id="root-fields" style="position:relative;"><a href="#root-fields" aria-label="root fields permalink"\n          class="anchor before"><svg aria-hidden="true" focusable="false" height="16" version="1.1" viewBox="0 0 16 16"\n            width="16">\n            <path fill-rule="evenodd"\n              d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z">\n            </path>\n          </svg></a>Root Fields</h3>\n      <p>Starting up are the root options in the TSConfig - these options relate to how your TypeScript or JavaScript\n        project is set up.</p>\n      <div>\n        <section class="compiler-option">\n          <h3 id="files-config"><a aria-label="Link to the compiler option: files" id="files" href="#files" name="files"\n              aria-labelledby="files-config">#</a> Files - <code>files</code></h3>\n          <div class="compiler-content">\n            <div class="markdown">\n              <p>Specifies an allowlist of files to include in the program. An error occurs if any of the files can’t be\n                found.</p>\n              <pre class="shiki light-plus tsconfig lsp" style="background-color: #FFFFFF; color: #000000"\n                tsconfig="true"><div class="code-container"><code><div class="line"><span style="color: #000000">{</span></div><div class="line"><span style="color: #000000">  </span><span style="color: #0451A5">"<a aria-hidden="true" tabindex="-1" href="https://www.typescriptlang.org/tsconfig#compilerOptions"><data-lsp lsp="The set of compiler options for your project">compilerOptions</data-lsp></a>"</span><span style="color: #000000">: {},</span></div><div class="line"><span style="color: #000000">  </span><span style="color: #0451A5">"<a aria-hidden="true" tabindex="-1" href="https://www.typescriptlang.org/tsconfig#files"><data-lsp lsp="Include a list of files. This does not support glob patterns, as opposed to [`include`](#include).">files</data-lsp></a>"</span><span style="color: #000000">: [</span></div><div class="line"><span style="color: #000000">    </span><span style="color: #A31515">"core.ts"</span><span style="color: #000000">,</span></div><div class="line"><span style="color: #000000">    </span><span style="color: #A31515">"sys.ts"</span><span style="color: #000000">,</span></div><div class="line"><span style="color: #000000">    </span><span style="color: #A31515">"types.ts"</span><span style="color: #000000">,</span></div><div class="line"><span style="color: #000000">    </span><span style="color: #A31515">"scanner.ts"</span><span style="color: #000000">,</span></div><div class="line"><span style="color: #000000">    </span><span style="color: #A31515">"parser.ts"</span><span style="color: #000000">,</span></div><div class="line"><span style="color: #000000">    </span><span style="color: #A31515">"utilities.ts"</span><span style="color: #000000">,</span></div><div class="line"><span style="color: #000000">    </span><span style="color: #A31515">"binder.ts"</span><span style="color: #000000">,</span></div><div class="line"><span style="color: #000000">    </span><span style="color: #A31515">"checker.ts"</span><span style="color: #000000">,</span></div><div class="line"><span style="color: #000000">    </span><span style="color: #A31515">"tsc.ts"</span></div><div class="line"><span style="color: #000000">  ]</span></div><div class="line"><span style="color: #000000">}</span></div></code></div></pre>\n              <p>This is useful when you only have a small number of files and don’t need to use a glob to reference\n                many files.\n                If you need that then use <a href="#include"><code>include</code></a>.</p>\n            </div>\n            <ul class="compiler-option-md">\n              <li><span>Default:</span>\n                <p><code>false</code></p>\n              </li>\n              <li><span>Related:</span>\n                <ul>\n                  <li>\n                    <p><a href="#include" aria-label="Jump to compiler option info for include"><code>include</code></a>\n                    </p>\n                  </li>\n                  <li>\n                    <p><a href="#exclude" aria-label="Jump to compiler option info for exclude"><code>exclude</code></a>\n                    </p>\n                  </li>\n                </ul>\n              </li>\n            </ul>\n          </div>\n        </section>\n        <section class="compiler-option">\n          <h3 id="extends-config"><a aria-label="Link to the compiler option: extends" id="extends" href="#extends"\n              name="extends" aria-labelledby="extends-config">#</a> Extends - <code>extends</code></h3>\n          <div class="compiler-content">\n            <div class="markdown">\n              <p>The value of <code>extends</code> is a string which contains a path to another configuration file to\n                inherit from.\n                The path may use Node.js style resolution.</p>\n              <p>The configuration from the base file are loaded first, then overridden by those in the inheriting\n                config file. All relative paths found in the configuration file will be resolved relative to the\n                configuration file they originated in.</p>\n              <p>It’s worth noting that <a href="#files"><code>files</code></a>, <a\n                  href="#include"><code>include</code></a>, and <a href="#exclude"><code>exclude</code></a> from the\n                inheriting config file <em>overwrite</em> those from the\n                base config file, and that circularity between configuration files is not allowed.</p>\n              <p>Currently, the only top-level property that is excluded from inheritance is <a\n                  href="#references"><code>references</code></a>.</p>\n              <h5 id="example" style="position:relative;"><a href="#example" aria-label="example permalink"\n                  class="anchor before"><svg aria-hidden="true" focusable="false" height="16" version="1.1"\n                    viewBox="0 0 16 16" width="16">\n                    <path fill-rule="evenodd"\n                      d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z">\n                    </path>\n                  </svg></a>Example</h5>\n              <p><code>configs/base.json</code>:</p>\n              <pre class="shiki light-plus tsconfig lsp" style="background-color: #FFFFFF; color: #000000"\n                tsconfig="true"><div class="code-container"><code><div class="line"><span style="color: #000000">{</span></div><div class="line"><span style="color: #000000">  </span><span style="color: #0451A5">"<a aria-hidden="true" tabindex="-1" href="https://www.typescriptlang.org/tsconfig#compilerOptions"><data-lsp lsp="The set of compiler options for your project">compilerOptions</data-lsp></a>"</span><span style="color: #000000">: {</span></div><div class="line"><span style="color: #000000">    </span><span style="color: #0451A5">"<a aria-hidden="true" tabindex="-1" href="https://www.typescriptlang.org/tsconfig#noImplicitAny"><data-lsp lsp="Enable error reporting for expressions and declarations with an implied `any` type.">noImplicitAny</data-lsp></a>"</span><span style="color: #000000">: </span><span style="color: #0000FF">true</span><span style="color: #000000">,</span></div><div class="line"><span style="color: #000000">    </span><span style="color: #0451A5">"<a aria-hidden="true" tabindex="-1" href="https://www.typescriptlang.org/tsconfig#strictNullChecks"><data-lsp lsp="When type checking, take into account `null` and `undefined`.">strictNullChecks</data-lsp></a>"</span><span style="color: #000000">: </span><span style="color: #0000FF">true</span></div><div class="line"><span style="color: #000000">  }</span></div><div class="line"><span style="color: #000000">}</span></div></code></div></pre>\n              <p><code>tsconfig.json</code>:</p>\n              <pre class="shiki light-plus tsconfig lsp" style="background-color: #FFFFFF; color: #000000"\n                tsconfig="true"><div class="code-container"><code><div class="line"><span style="color: #000000">{</span></div><div class="line"><span style="color: #000000">  </span><span style="color: #0451A5">"<a aria-hidden="true" tabindex="-1" href="https://www.typescriptlang.org/tsconfig#extends"><data-lsp lsp="Specify one or more path or node module references to base configuration files from which settings are inherited.">extends</data-lsp></a>"</span><span style="color: #000000">: </span><span style="color: #A31515">"./configs/base"</span><span style="color: #000000">,</span></div><div class="line"><span style="color: #000000">  </span><span style="color: #0451A5">"<a aria-hidden="true" tabindex="-1" href="https://www.typescriptlang.org/tsconfig#files"><data-lsp lsp="Include a list of files. This does not support glob patterns, as opposed to [`include`](#include).">files</data-lsp></a>"</span><span style="color: #000000">: [</span><span style="color: #A31515">"main.ts"</span><span style="color: #000000">, </span><span style="color: #A31515">"supplemental.ts"</span><span style="color: #000000">]</span></div><div class="line"><span style="color: #000000">}</span></div></code></div></pre>\n              <p><code>tsconfig.nostrictnull.json</code>:</p>\n              <pre class="shiki light-plus tsconfig lsp" style="background-color: #FFFFFF; color: #000000"\n                tsconfig="true"><div class="code-container"><code><div class="line"><span style="color: #000000">{</span></div><div class="line"><span style="color: #000000">  </span><span style="color: #0451A5">"<a aria-hidden="true" tabindex="-1" href="https://www.typescriptlang.org/tsconfig#extends"><data-lsp lsp="Specify one or more path or node module references to base configuration files from which settings are inherited.">extends</data-lsp></a>"</span><span style="color: #000000">: </span><span style="color: #A31515">"./tsconfig"</span><span style="color: #000000">,</span></div><div class="line"><span style="color: #000000">  </span><span style="color: #0451A5">"<a aria-hidden="true" tabindex="-1" href="https://www.typescriptlang.org/tsconfig#compilerOptions"><data-lsp lsp="The set of compiler options for your project">compilerOptions</data-lsp></a>"</span><span style="color: #000000">: {</span></div><div class="line"><span style="color: #000000">    </span><span style="color: #0451A5">"<a aria-hidden="true" tabindex="-1" href="https://www.typescriptlang.org/tsconfig#strictNullChecks"><data-lsp lsp="When type checking, take into account `null` and `undefined`.">strictNullChecks</data-lsp></a>"</span><span style="color: #000000">: </span><span style="color: #0000FF">false</span></div><div class="line"><span style="color: #000000">  }</span></div><div class="line"><span style="color: #000000">}</span></div></code></div></pre>\n              <p>Properties with relative paths found in the configuration file, which aren’t excluded from inheritance,\n                will be resolved relative to the configuration file they originated in.</p>\n            </div>\n            <ul class="compiler-option-md">\n              <li><span>Default:</span>\n                <p><code>false</code></p>\n              </li>\n              <li><span>Released:</span>\n                <p><a aria-label="Release notes for TypeScript 2.1"\n                    href="/docs/handbook/release-notes/typescript-2-1.html">2.1</a></p>\n              </li>\n            </ul>\n          </div>\n        </section>\n        <section class="compiler-option">\n          <h3 id="include-config"><a aria-label="Link to the compiler option: include" id="include" href="#include"\n              name="include" aria-labelledby="include-config">#</a> Include - <code>include</code></h3>\n          <div class="compiler-content">\n            <div class="markdown">\n              <p>Specifies an array of filenames or patterns to include in the program.\n                These filenames are resolved relative to the directory containing the <code>tsconfig.json</code> file.\n              </p>\n              <pre class="shiki light-plus"\n                style="background-color: #FFFFFF; color: #000000"><div class="language-id">json</div><div class="code-container"><code><div class="line"><span style="color: #000000">{</span></div><div class="line"><span style="color: #000000">  </span><span style="color: #0451A5">"include"</span><span style="color: #000000">: [</span><span style="color: #A31515">"src/**/*"</span><span style="color: #000000">, </span><span style="color: #A31515">"tests/**/*"</span><span style="color: #000000">]</span></div><div class="line"><span style="color: #000000">}</span></div></code></div></pre>\n              <p>Which would include:</p>\n              <!-- TODO: #135\n```diff\n  .\n- ├── scripts\n- │   ├── lint.ts\n- │   ├── update_deps.ts\n- │   └── utils.ts\n+ ├── src\n+ │   ├── client\n+ │   │    ├── index.ts\n+ │   │    └── utils.ts\n+ │   ├── server\n+ │   │    └── index.ts\n+ ├── tests\n+ │   ├── app.test.ts\n+ │   ├── utils.ts\n+ │   └── tests.d.ts\n- ├── package.json\n- ├── tsconfig.json\n- └── yarn.lock\n``` -->\n              <pre class="shiki light-plus"\n                style="background-color: #FFFFFF; color: #000000"><div class="code-container"><code><div class="line"><span style="color: undefined">.</span></div><div class="line"><span style="color: undefined">├── scripts                ⨯</span></div><div class="line"><span style="color: undefined">│   ├── lint.ts            ⨯</span></div><div class="line"><span style="color: undefined">│   ├── update_deps.ts     ⨯</span></div><div class="line"><span style="color: undefined">│   └── utils.ts           ⨯</span></div><div class="line"><span style="color: undefined">├── src                    ✓</span></div><div class="line"><span style="color: undefined">│   ├── client             ✓</span></div><div class="line"><span style="color: undefined">│   │    ├── index.ts      ✓</span></div><div class="line"><span style="color: undefined">│   │    └── utils.ts      ✓</span></div><div class="line"><span style="color: undefined">│   ├── server             ✓</span></div><div class="line"><span style="color: undefined">│   │    └── index.ts      ✓</span></div><div class="line"><span style="color: undefined">├── tests                  ✓</span></div><div class="line"><span style="color: undefined">│   ├── app.test.ts        ✓</span></div><div class="line"><span style="color: undefined">│   ├── utils.ts           ✓</span></div><div class="line"><span style="color: undefined">│   └── tests.d.ts         ✓</span></div><div class="line"><span style="color: undefined">├── package.json</span></div><div class="line"><span style="color: undefined">├── tsconfig.json</span></div><div class="line"><span style="color: undefined">└── yarn.lock</span></div></code></div></pre>\n              <p><code>include</code> and <code>exclude</code> support wildcard characters to make glob patterns:</p>\n              <ul>\n                <li><code>*</code> matches zero or more characters (excluding directory separators)</li>\n                <li><code>?</code> matches any one character (excluding directory separators)</li>\n                <li><code>**/</code> matches any directory nested to any level</li>\n              </ul>\n              <p>If the last path segment in a pattern does not contain a file extension or wildcard character, then it\n                is treated as a directory, and files with supported extensions inside that directory are included (e.g.\n                <code>.ts</code>, <code>.tsx</code>, and <code>.d.ts</code> by default, with <code>.js</code> and\n                <code>.jsx</code> if <a href="#allowJs"><code>allowJs</code></a> is set to true).</p>\n            </div>\n            <ul class="compiler-option-md">\n              <li><span>Default:</span>\n                <p><code>[]</code> if <a href="#files"><code>files</code></a> is specified; <code>**/*</code> otherwise.\n                </p>\n              </li>\n              <li><span>Related:</span>\n                <ul>\n                  <li>\n                    <p><a href="#files" aria-label="Jump to compiler option info for files"><code>files</code></a></p>\n                  </li>\n                  <li>\n                    <p><a href="#exclude" aria-label="Jump to compiler option info for exclude"><code>exclude</code></a>\n                    </p>\n                  </li>\n                </ul>\n              </li>\n              <li><span>Released:</span>\n                <p><a aria-label="Release notes for TypeScript 2.0"\n                    href="/docs/handbook/release-notes/typescript-2-0.html">2.0</a></p>\n              </li>\n            </ul>\n          </div>\n        </section>\n        <section class="compiler-option">\n          <h3 id="exclude-config"><a aria-label="Link to the compiler option: exclude" id="exclude" href="#exclude"\n              name="exclude" aria-labelledby="exclude-config">#</a> Exclude - <code>exclude</code></h3>\n          <div class="compiler-content">\n            <div class="markdown">\n              <p>Specifies an array of filenames or patterns that should be skipped when resolving <a\n                  href="#include"><code>include</code></a>.</p>\n              <p><strong>Important</strong>: <code>exclude</code> <em>only</em> changes which files are included as a\n                result of the <a href="#include"><code>include</code></a> setting.\n                A file specified by <code>exclude</code> can still become part of your codebase due to an\n                <code>import</code> statement in your code, a <code>types</code> inclusion, a\n                <code>/// &lt;reference</code> directive, or being specified in the <a\n                  href="#files"><code>files</code></a> list.</p>\n              <p>It is not a mechanism that <strong>prevents</strong> a file from being included in the codebase - it\n                simply changes what the <a href="#include"><code>include</code></a> setting finds.</p>\n            </div>\n            <ul class="compiler-option-md">\n              <li><span>Default:</span>\n                <p>node_modules bower_components jspm_packages <a href="#outDir"><code>outDir</code></a></p>\n              </li>\n              <li><span>Related:</span>\n                <ul>\n                  <li>\n                    <p><a href="#include" aria-label="Jump to compiler option info for include"><code>include</code></a>\n                    </p>\n                  </li>\n                  <li>\n                    <p><a href="#files" aria-label="Jump to compiler option info for files"><code>files</code></a></p>\n                  </li>\n                </ul>\n              </li>\n            </ul>\n          </div>\n        </section>\n        <section class="compiler-option">\n          <h3 id="references-config"><a aria-label="Link to the compiler option: references" id="references"\n              href="#references" name="references" aria-labelledby="references-config">#</a> References -\n            <code>references</code></h3>\n          <div class="compiler-content">\n            <div class="markdown">\n              <p>Project references are a way to structure your TypeScrip

In [172]:
PAGE_URL = "https://www.typescriptlang.org/tsconfig"

soup = BeautifulSoup(html, "html.parser")

entries = []

top = []
for section in soup.div.children:
    category_text = ""
    if section.name is None:
        continue
    for a in section.find_all("a"):
        if a["href"].startswith("#") or a["href"].startswith("/"):
            a["href"] = PAGE_URL + a["href"]
    article = section.article
    section_name = article.contents[1]
    section_name_html = f"<p>{section_name.text.strip()}</p>"
    section_definition = BeautifulSoup(
        "\n".join([str(e) for e in article.find_all("p", recursive=False)]),
        "html.parser",
    )
    section_definition_html = section_definition.prettify()
    section_summary_text = re.split(r"\.\s", section_definition.text)[0] + "."
    section_summary_text = re.sub(r"\s+", " ", section_summary_text)
    section_summary_text = re.sub(r"\.+", ".", section_summary_text)
    section_summary_html = f"<p>{section_summary_text}</p>"
    entries.append(
        {
            "type_text": "Section",
            "type_html": "<p>Section</p>",
            "parent_html": "",
            "category_text": "",
            "category_html": "",
            "title_elem": section_name,
            "title_html": section_name_html,
            "definition_elem": section_definition,
            "definition_html": section_definition_html,
            "summary_html": section_summary_html,
        }
    )
    for prop in section.div.children:
        if isinstance(prop, NavigableString):
            continue
        if prop.name == "div":
            category_text = re.sub(r"\s+", " ", prop.h2.text.strip())
            category_text = (
                category_text[1:]
                if category_text.startswith("#")
                else category_text
            )
        if prop.name == "section":
            href = prop.a["href"]
            title_code = prop.h3.code
            title_text = title_code.text
            title_elem = BeautifulSoup(f'<a href="{href}"></a>', "html.parser")
            title_elem.append(title_code)
            title_html = title_elem.prettify()
            compiler_content = prop.find(class_="compiler-content")

            summary_elem = compiler_content.find("p")
            if summary_elem is None:
                summary_elem = BeautifulSoup(
                    f"<p>{compiler_content.text}</p>", "html.parser"
                )
            if summary_elem.find("p") is not None:
                for sub in summary_elem.descendants:
                    if isinstance(sub, NavigableString):
                        replaced = sub.replace(title_text, "___")
                        sub.replace_with(replaced)
                        # match = re.match(r"(.*?[\.\!\?])(\s|$)", sub)
                        # if match:
                        #     print(match)
                        #     summary_elem = match.group(1)
                        #     break
            for link in compiler_content.find_all(class_="playground-link"):
                link.decompose()

            del compiler_content["class"]
            for sub in compiler_content.descendants:
                if hasattr(sub, "class"):
                    if "language-id" not in sub.get("class", []):
                        del sub["class"]
                if hasattr(sub, "style"):
                    del sub["style"]
            definition_elem = compiler_content
            definition_html = compiler_content.prettify()
            entries.append(
                {
                    "type_text": "Property",
                    "type_html": "<p>Property</p>",
                    "parent_html": section_name_html,
                    "category_text": category_text,
                    "category_html": (
                        ""
                        if category_text == ""
                        else f"<p>{category_text}</p>"
                    ),
                    "title_elem": title_elem,
                    "title_html": title_html,
                    "definition_elem": definition_elem,
                    "definition_html": definition_html,
                    "summary_html": summary_elem.prettify(),
                }
            )
            # markdown = compiler_content.find(class_="markdown")
            # aside = compiler_content.find(class_="compiler-option-md")

            # print("-c", category_text, ": ", definition_text)

for entry in entries[88::100]:
    if entry["type_text"] != "Property":
        continue
    print("--", entry["title_html"])
    display(HTML(entry["title_html"]))
    display(HTML(entry["definition_html"]))
    print(entry["definition_html"])
    print("\n" * 2)

-- <a href="https://www.typescriptlang.org/tsconfig#jsxFactory">
</a>
<code>
 jsxFactory
</code>

<div>
 <div>
  <p>
   Changes the function called in
   <code>
    .js
   </code>
   files when compiling JSX Elements using the classic JSX
                runtime.
                The most common change is to use
   <code>
    "h"
   </code>
   or
   <code>
    "preact.h"
   </code>
   instead of the default
   <code>
    "React.createElement"
   </code>
   if using
   <code>
    preact
   </code>
   .
  </p>
  <p>
   For example, this TSX file:
  </p>
  <pre><div class="language-id">tsx</div><div><code><div><span>import</span><span> { </span><span>h</span><span> } </span><span>from</span><span> </span><span>"preact"</span><span>;</span></div><div></div><div><span>const</span><span> </span><span>HelloWorld</span><span> = () </span><span>=&gt;</span><span> </span><span>&lt;div&gt;</span><span>Hello</span><span>&lt;/div&gt;</span><span>;</span></div></code></div></pre>
  <p>
   With
   <code>
    jsxFactory: "h"
   </code>
   looks like:
  </p>
  <pre><div class="language-id">tsx</div><div><code><div><span>const</span><span> </span><span>preact_1</span><span> = </span><span>require</span><span>(</span><span>"preact"</span><span>);</span></div><div><span>const</span><span> </span><span>HelloWorld</span><span> = () </span><span>=&gt;</span><span> (</span><span>0</span><span>, </span><span>preact_1</span><span>.</span><span>h</span><span>)(</span><span>"div"</span><span>, </span><span>null</span><span>, </span><span>"Hello"</span><span>);</span></div><div> </div></code></div></pre>
  <p>
   This option can be used on a per-file basis too similar to
   <a href="https://babeljs.io/docs/en/babel-plugin-transform-react-jsx#custom">
    Babel’s
    <code>
     /** @jsx h */
    </code>
    directive
   </a>
   .
  </p>
  <pre><div class="language-id">tsx</div><div><code><div><span>/** </span><span>@jsx</span><span> h */</span></div><div><span>import</span><span> { </span><span><data-lsp lsp="import h">h</data-lsp></span><span> } </span><span>from</span><span> </span><span><data-err>"preact"</data-err></span><span>;</span></div><span><span>Cannot find module 'preact' or its corresponding type declarations.</span><span>2307</span></span><span>Cannot find module 'preact' or its corresponding type declarations.</span><div> </div><div><span>const</span><span> </span><span><data-lsp lsp="const HelloWorld: () =&gt; React.JSX.Element">HelloWorld</data-lsp></span><span> = () </span><span>=&gt;</span><span> </span><span>&lt;<data-lsp lsp="(property) JSX.IntrinsicElements.div: React.DetailedHTMLProps&lt;React.HTMLAttributes&lt;HTMLDivElement&gt;, HTMLDivElement&gt;">div</data-lsp>&gt;</span><span>Hello</span><span>&lt;/<data-lsp lsp="(property) JSX.IntrinsicElements.div: React.DetailedHTMLProps&lt;React.HTMLAttributes&lt;HTMLDivElement&gt;, HTMLDivElement&gt;">div</data-lsp>&gt;</span><span>;</span></div></code></div></pre>
  <p>
   The factory chosen will also affect where the
   <code>
    JSX
   </code>
   namespace is looked up (for type
                checking information) before falling back to the global one.
  </p>
  <p>
   If the factory is defined as
   <code>
    React.createElement
   </code>
   (the default), the compiler will check
                for
   <code>
    React.JSX
   </code>
   before checking for a global
   <code>
    JSX
   </code>
   . If the factory is defined as
   <code>
    h
   </code>
   , it will check for
   <code>
    h.JSX
   </code>
   before a global
   <code>
    JSX
   </code>
   .
  </p>
 </div>
 <ul>
  <li>
   <span>
    Default:
   </span>
   <p>
    <code>
     React.createElement
    </code>
   </p>
  </li>
  <li>
   <span>
    Allowed:
   </span>
   <ul>
    <li>
     <p>
      Any identifier or dotted identifier.
     </p>
    </li>
   </ul>
  </li>
  <li>
   <span>
    Related:
   </span>
   <ul>
    <li>
     <p>
      <a aria-label="Jump to compiler option info for jsx" href="https://www.typescriptlang.org/tsconfig#jsx">
       <code>
        jsx
       </code>
      </a>
     </p>
    </li>
    <li>
     <p>
      <a aria-label="Jump to compiler option info for jsxFragmentFactory" href="https://www.typescriptlang.org/tsconfig#jsxFragmentFactory">
       <code>
        jsxFragmentFactory
       </code>
      </a>
     </p>
    </li>
    <li>
     <p>
      <a aria-label="Jump to compiler option info for jsxImportSource" href="https://www.typescriptlang.org/tsconfig#jsxImportSource">
       <code>
        jsxImportSource
       </code>
      </a>
     </p>
    </li>
   </ul>
  </li>
 </ul>
</div>

In [173]:
df = pd.DataFrame(entries)
df.drop(columns=df.filter(regex="_elem$").columns, inplace=True)
df.drop(columns=df.filter(regex="_text$").columns, inplace=True)
df.rename(
    columns={
        # "type_text": "TypeText",
        "type_html": "TypeHtml",
        "parent_html": "ParentHtml",
        # "category_text": "CategoryText",
        "category_html": "CategoryHtml",
        "title_html": "TitleHtml",
        "definition_html": "DefinitionHtml",
        "summary_html": "SummaryHtml",
    },
    inplace=True,
)
df["Tags"] = "WebScraped Typescript-5.5"
with pd.option_context(*options):
    display(df.head())
df[df["TitleHtml"].str.contains("jsxFactory")]

,TypeHtml,ParentHtml,CategoryHtml,TitleHtml,DefinitionHtml,SummaryHtml,Tags
0,<p>Section</p>,,,<p>Root Fields</p>,<p>\n Starting up are the root options in the ...,<p>Starting up are the root options in the TSC...,WebScraped Typescript-5.5
1,<p>Property</p>,<p>Root Fields</p>,,"<a href=""https://www.typescriptlang.org/tsconf...",<div>\n <div>\n <p>\n Specifies an allowlis...,<p>\n Specifies an allowlist of files to inclu...,WebScraped Typescript-5.5
2,<p>Property</p>,<p>Root Fields</p>,,"<a href=""https://www.typescriptlang.org/tsconf...",<div>\n <div>\n <p>\n The value of\n <cod...,<p>\n The value of\n <code>\n extends\n </cod...,WebScraped Typescript-5.5
3,<p>Property</p>,<p>Root Fields</p>,,"<a href=""https://www.typescriptlang.org/tsconf...",<div>\n <div>\n <p>\n Specifies an array of...,<p>\n Specifies an array of filenames or patte...,WebScraped Typescript-5.5
4,<p>Property</p>,<p>Root Fields</p>,,"<a href=""https://www.typescriptlang.org/tsconf...",<div>\n <div>\n <p>\n Specifies an array of...,<p>\n Specifies an array of filenames or patte...,WebScraped Typescript-5.5

,TypeHtml,ParentHtml,CategoryHtml,TitleHtml,DefinitionHtml,SummaryHtml,Tags
88,<p>Property</p>,<p>Compiler Options</p>,<p>Language and Environment</p>,"<a href=""https://www.typescriptlang.org/tsconf...",<div>\n <div>\n <p>\n Changes the function ...,<p>\n Changes the function called in\n <code>\...,WebScraped Typescript-5.5

In [174]:
df.to_csv(target_abspath, sep="|", index=False, header=False)