# Gdp

In [1]:
import sys
from src.utils.db import Db
import pandas as pd
import matplotlib as mpl
from typing import Union, cast
import numpy as np
from src.utils import theme
import more_itertools as mi

db = Db("gdp")
df = {}

# Slope and Intercept through SQL methods

In [2]:
db.view_select(
    df,
    "view.country.window-slope-intercept",
    ["Country", "Year", "Value", "Slope", "Intercept"],
    ["Country", "Year"],
)["raw"]

                     Intercept      Slope        Value
Country     Year
Afghanistan 2010  25709.123794 -12.491152   542.871030
            2011  25709.123794 -12.491152   525.426983
            2012  25709.123794 -12.491152   568.929021
            2013  25709.123794 -12.491152   580.603833
            2014  25709.123794 -12.491152   575.146246
...                        ...        ...          ...
Zimbabwe    2019 -21733.232922  11.438149  1350.309851
            2020 -21733.232922  11.438149  1224.272314
            2021 -21733.232922  11.438149  1305.220113
            2022 -21733.232922  11.438149  1361.914530
            2023 -21733.232922  11.438149  1410.737311

[3576 rows x 3 columns]

In [3]:
db.view_select(
    df,
    "view.country.aggregate-slope-intercept",
    ["Country", "Slope", "Intercept"],
    ["Country"],
)["raw"]

                                 Intercept       Slope
Country
Afghanistan                   25709.123794  -12.491152
Africa Eastern and Southern    7369.505637   -2.937568
Africa Western and Central   -11775.450007    6.722763
Albania                     -260649.353630  131.374563
Algeria                       -2386.756427    3.460026
...                                    ...         ...
West Bank and Gaza            22532.742683   -9.587919
World                       -327791.768086  167.704111
Yemen, Rep.                  240036.254614 -118.336845
Zambia                       -10829.030269    6.003864
Zimbabwe                     -21733.232922   11.438149

[260 rows x 2 columns]

In [4]:
db.view_select(
    df,
    "view.country.aggregate-merge-slope-intercept",
    ["Country", "Year", "Value", "Slope", "Intercept"],
    ["Country", "Year"],
)["raw"]

                                     Intercept      Slope        Value
Country                     Year
Africa Eastern and Southern 2023   7369.505637  -2.937568  1418.363737
                            2022   7369.505637  -2.937568  1421.589728
                            2021   7369.505637  -2.937568  1408.860838
                            2020   7369.505637  -2.937568  1383.377818
                            2019   7369.505637  -2.937568  1463.139549
...                                        ...        ...          ...
Zimbabwe                    2014 -21733.232922  11.438149  1377.254560
                            2013 -21733.232922  11.438149  1375.851342
                            2012 -21733.232922  11.438149  1352.135136
                            2011 -21733.232922  11.438149  1187.318407
                            2010 -21733.232922  11.438149  1054.397915

[3576 rows x 3 columns]

Check if two dataframes are equal

In [48]:
# TODO ANKI two tables are equal until round(8)
dfs = [
    df[name]["raw"]
    .copy()
    .round(8)
    .sort_values(["Country", "Year"])
    .reset_index()
    for name in [
        "view.country.window-slope-intercept",
        "view.country.aggregate-merge-slope-intercept",
    ]
]
# TODO ANKI
print("".join(str(x) for x in mi.intersperse("\n", [d.dtypes for d in dfs])))

# TODO ANKI
print(dfs[0].dtypes.equals(dfs[1].dtypes))

print(dfs[0].columns == dfs[1].columns)
print(dfs[0].index == dfs[1].index)

# TODO ANKI
print(dfs[0].compare(dfs[1]))
# .head().to_csv(sys.stdout)

# TODO ANKI
dfs[0].equals(dfs[1])

Country       object
Year           int64
Intercept    float64
Slope        float64
Value        float64
dtype: object
Country       object
Year           int64
Intercept    float64
Slope        float64
Value        float64
dtype: object
True
[ True  True  True  True  True]
[ True  True  True ...  True  True  True]
         Intercept
              self         other
335   1.074528e+06  1.074528e+06
336   1.074528e+06  1.074528e+06
337   1.074528e+06  1.074528e+06
338   1.074528e+06  1.074528e+06
339   1.074528e+06  1.074528e+06
340   1.074528e+06  1.074528e+06
341   1.074528e+06  1.074528e+06
342   1.074528e+06  1.074528e+06
343   1.074528e+06  1.074528e+06
344   1.074528e+06  1.074528e+06
345   1.074528e+06  1.074528e+06
346   1.074528e+06  1.074528e+06
347   1.074528e+06  1.074528e+06
348   1.074528e+06  1.074528e+06
1351 -2.503469e+04 -2.503469e+04
1352 -2.503469e+04 -2.503469e+04
1353 -2.503469e+04 -2.503469e+04
1354 -2.503469e+04 -2.503469e+04
1355 -2.503469e+04 -2.503469e+04
1356 -2.503469e+04 -2.503469e+04
1357 -2.503469e+04 -2.503469e+04
1358 -2.503469e+04 -2.503469e+04
1359 -2.503469e+04 -2.503469e+04
1360 -2.503469e+04 -2.503469e+04
1361 -2.503469e+04 -2.503469e+04
1362 -2.503469e+04 -2.503469e+04
1363 -2.503469e+04 -2.503469e+04
1364 -2.503469e+04 -2.503469e+04
2217 -1.029830e+07 -1.029830e+07
2218 -1.029830e+07 -1.029830e+07
2219 -1.029830e+07 -1.029830e+07
2220 -1.029830e+07 -1.029830e+07
2221 -1.029830e+07 -1.029830e+07
2222 -1.029830e+07 -1.029830e+07
2223 -1.029830e+07 -1.029830e+07
2224 -1.029830e+07 -1.029830e+07
2225 -1.029830e+07 -1.029830e+07
2226 -1.029830e+07 -1.029830e+07
2227 -1.029830e+07 -1.029830e+07
2228 -1.029830e+07 -1.029830e+07
2229 -1.029830e+07 -1.029830e+07
2230 -1.029830e+07 -1.029830e+07
2497 -3.969597e+05 -3.969597e+05
2498 -3.969597e+05 -3.969597e+05
2499 -3.969597e+05 -3.969597e+05
2500 -3.969597e+05 -3.969597e+05
2501 -3.969597e+05 -3.969597e+05
2502 -3.969597e+05 -3.969597e+05
2503 -3.969597e+05 -3.969597e+05
2504 -3.969597e+05 -3.969597e+05
2505 -3.969597e+05 -3.969597e+05
2506 -3.969597e+05 -3.969597e+05
2507 -3.969597e+05 -3.969597e+05
2508 -3.969597e+05 -3.969597e+05
2509 -3.969597e+05 -3.969597e+05
2510 -3.969597e+05 -3.969597e+05

False