# Mdn Window api

In [1]:
from bs4 import BeautifulSoup
from requests import get
import pandas as pd
import json
import base64
from fetch import fetch_root_page_from_file, get_urls, get_sections_urls
from store import write_specs, get_sections_content, load_soups
from process import produce_df

ROOT = "https://developer.mozilla.org"
REPO_ROOT = "/utkusarioglu-com/workshops/backtesting-workshop"
FILE_ROOT = f"{REPO_ROOT}/assets/mdn"
ARTIFACTS_ROOT = f"{REPO_ROOT}/artifacts"

## Get list from web

In [2]:
# page = get(f"{ROOT}/en-US/docs/Web/API/Window")
# soup = BeautifulSoup(page.text)

## Get list from file

In [3]:
soup = fetch_root_page_from_file(FILE_ROOT)
soup.title

## Produce section titles and urls

In [4]:
sections = soup.find_all("li", class_="toggle")
sections_urls = get_sections_urls(ROOT, sections)
sections_urls

[{'section_title': 'Instance properties',
  'items': [{'link_title': 'caches',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/caches'},
   {'link_title': 'closed',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/closed'},
   {'link_title': 'console',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/console'},
   {'link_title': 'cookieStore',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/cookieStore'},
   {'link_title': 'credentialless',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/credentialless'},
   {'link_title': 'crossOriginIsolated',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/crossOriginIsolated'},
   {'link_title': 'crypto',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/crypto'},
   {'link_title': 'customElements',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/customElements'},
   {'link_title': 'devicePixelRatio',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio'},
   {'link_title': 'document',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/document'},
   {'link_title': 'documentPictureInPicture',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/documentPictureInPicture'},
   {'link_title': 'event',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/event'},
   {'link_title': 'external',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/external'},
   {'link_title': 'fence',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/fence'},
   {'link_title': 'frameElement',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/frameElement'},
   {'link_title': 'frames',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/frames'},
   {'link_title': 'fullScreen',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/fullScreen'},
   {'link_title': 'history',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/history'},
   {'link_title': 'indexedDB',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/indexedDB'},
   {'link_title': 'innerHeight',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/innerHeight'},
   {'link_title': 'innerWidth',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/innerWidth'},
   {'link_title': 'isSecureContext',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/isSecureContext'},
   {'link_title': 'launchQueue',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/launchQueue'},
   {'link_title': 'length',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/length'},
   {'link_title': 'localStorage',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage'},
   {'link_title': 'location',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/location'},
   {'link_title': 'locationbar',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/locationbar'},
   {'link_title': 'menubar',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/menubar'},
   {'link_title': 'mozInnerScreenX',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/mozInnerScreenX'},
   {'link_title': 'mozInnerScreenY',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/mozInnerScreenY'},
   {'link_title': 'name',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/name'},
   {'link_title': 'navigation',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/navigation'},
   {'link_title': 'navigator',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/navigator'},
   {'link_title': 'opener',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/opener'},
   {'link_title': 'orientation',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/orientation'},
   {'link_title': 'origin',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/origin'},
   {'link_title': 'originAgentCluster',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/originAgentCluster'},
   {'link_title': 'outerHeight',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/outerHeight'},
   {'link_title': 'outerWidth',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/outerWidth'},
   {'link_title': 'parent',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/parent'},
   {'link_title': 'performance',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/performance'},
   {'link_title': 'personalbar',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/personalbar'},
   {'link_title': 'scheduler',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/scheduler'},
   {'link_title': 'screen',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/screen'},
   {'link_title': 'screenLeft',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/screenLeft'},
   {'link_title': 'screenTop',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/screenTop'},
   {'link_title': 'screenX',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/screenX'},
   {'link_title': 'screenY',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/screenY'},
   {'link_title': 'scrollbars',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollbars'},
   {'link_title': 'scrollMaxX',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollMaxX'},
   {'link_title': 'scrollMaxY',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollMaxY'},
   {'link_title': 'scrollX',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollX'},
   {'link_title': 'scrollY',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY'},
   {'link_title': 'self',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/self'},
   {'link_title': 'sessionStorage',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage'},
   {'link_title': 'sharedStorage',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/sharedStorage'},
   {'link_title': 'sidebar',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/sidebar'},
   {'link_title': 'speechSynthesis',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/speechSynthesis'},
   {'link_title': 'status',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/status'},
   {'link_title': 'statusbar',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/statusbar'},
   {'link_title': 'toolbar',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/toolbar'},
   {'link_title': 'top',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/top'},
   {'link_title': 'trustedTypes',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/trustedTypes'},
   {'link_title': 'visualViewport',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/visualViewport'},
   {'link_title': 'window',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/window'}]},
 {'section_title': 'Instance methods',
  'items': [{'link_title': 'alert()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/alert'},
   {'link_title': 'atob()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/atob'},
   {'link_title': 'back()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/back'},
   {'link_title': 'blur()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/blur'},
   {'link_title': 'btoa()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/btoa'},
   {'link_title': 'cancelAnimationFrame()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelAnimationFrame'},
   {'link_title': 'cancelIdleCallback()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelIdleCallback'},
   {'link_title': 'captureEvents()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/captureEvents'},
   {'link_title': 'clearImmediate()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/clearImmediate'},
   {'link_title': 'close()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/close'},
   {'link_title': 'confirm()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm'},
   {'link_title': 'dump()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/dump'},
   {'link_title': 'find()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/find'},
   {'link_title': 'focus()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/focus'},
   {'link_title': 'forward()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/forward'},
   {'link_title': 'getComputedStyle()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle'},
   {'link_title': 'getDefaultComputedStyle()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/getDefaultComputedStyle'},
   {'link_title': 'getScreenDetails()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/getScreenDetails'},
   {'link_title': 'getSelection()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection'},
   {'link_title': 'matchMedia()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia'},
   {'link_title': 'moveBy()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/moveBy'},
   {'link_title': 'moveTo()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/moveTo'},
   {'link_title': 'open()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/open'},
   {'link_title': 'postMessage()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage'},
   {'link_title': 'print()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/print'},
   {'link_title': 'prompt()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt'},
   {'link_title': 'queryLocalFonts()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/queryLocalFonts'},
   {'link_title': 'releaseEvents()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/releaseEvents'},
   {'link_title': 'requestAnimationFrame()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame'},
   {'link_title': 'requestFileSystem()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/requestFileSystem'},
   {'link_title': 'requestIdleCallback()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback'},
   {'link_title': 'resizeBy()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/resizeBy'},
   {'link_title': 'resizeTo()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/resizeTo'},
   {'link_title': 'scroll()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll'},
   {'link_title': 'scrollBy()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollBy'},
   {'link_title': 'scrollByLines()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollByLines'},
   {'link_title': 'scrollByPages()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollByPages'},
   {'link_title': 'scrollTo()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo'},
   {'link_title': 'setImmediate()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate'},
   {'link_title': 'setResizable()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/setResizable'},
   {'link_title': 'showDirectoryPicker()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/showDirectoryPicker'},
   {'link_title': 'showModalDialog()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/showModalDialog'},
   {'link_title': 'showOpenFilePicker()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker'},
   {'link_title': 'showSaveFilePicker()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker'},
   {'link_title': 'sizeToContent()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/sizeToContent'},
   {'link_title': 'stop()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/stop'},
   {'link_title': 'updateCommands()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/updateCommands'},
   {'link_title': 'webkitConvertPointFromNodeToPage()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/webkitConvertPointFromNodeToPage'},
   {'link_title': 'webkitConvertPointFromPageToNode()',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/webkitConvertPointFromPageToNode'}]},
 {'section_title': 'Events',
  'items': [{'link_title': 'afterprint',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/afterprint_event'},
   {'link_title': 'appinstalled',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/appinstalled_event'},
   {'link_title': 'beforeinstallprompt',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeinstallprompt_event'},
   {'link_title': 'beforeprint',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeprint_event'},
   {'link_title': 'beforeunload',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event'},
   {'link_title': 'blur',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/blur_event'},
   {'link_title': 'copy',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/copy_event'},
   {'link_title': 'cut',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/cut_event'},
   {'link_title': 'devicemotion',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/devicemotion_event'},
   {'link_title': 'deviceorientation',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/deviceorientation_event'},
   {'link_title': 'deviceorientationabsolute',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/deviceorientationabsolute_event'},
   {'link_title': 'error',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event'},
   {'link_title': 'focus',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/focus_event'},
   {'link_title': 'gamepadconnected',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/gamepadconnected_event'},
   {'link_title': 'gamepaddisconnected',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/gamepaddisconnected_event'},
   {'link_title': 'hashchange',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event'},
   {'link_title': 'languagechange',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/languagechange_event'},
   {'link_title': 'load',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event'},
   {'link_title': 'message',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/message_event'},
   {'link_title': 'messageerror',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/messageerror_event'},
   {'link_title': 'offline',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/offline_event'},
   {'link_title': 'online',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/online_event'},
   {'link_title': 'orientationchange',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/orientationchange_event'},
   {'link_title': 'pagehide',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/pagehide_event'},
   {'link_title': 'pageshow',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/pageshow_event'},
   {'link_title': 'paste',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/paste_event'},
   {'link_title': 'popstate',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event'},
   {'link_title': 'rejectionhandled',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/rejectionhandled_event'},
   {'link_title': 'resize',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event'},
   {'link_title': 'storage',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event'},
   {'link_title': 'unhandledrejection',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event'},
   {'link_title': 'unload',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event'},
   {'link_title': 'vrdisplayactivate',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/vrdisplayactivate_event'},
   {'link_title': 'vrdisplayconnect',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/vrdisplayconnect_event'},
   {'link_title': 'vrdisplaydeactivate',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/vrdisplaydeactivate_event'},
   {'link_title': 'vrdisplaydisconnect',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/vrdisplaydisconnect_event'},
   {'link_title': 'vrdisplaypresentchange',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Window/vrdisplaypresentchange_event'}]},
 {'section_title': 'Inheritance',
  'items': [{'link_title': 'EventTarget',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/EventTarget'}]},
 {'section_title': 'Related pages for DOM',
  'items': [{'link_title': 'AbortController',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/AbortController'},
   {'link_title': 'AbortSignal',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal'},
   {'link_title': 'AbstractRange',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/AbstractRange'},
   {'link_title': 'Attr',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Attr'},
   {'link_title': 'CDATASection',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/CDATASection'},
   {'link_title': 'CharacterData',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/CharacterData'},
   {'link_title': 'Comment',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Comment'},
   {'link_title': 'CustomEvent',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent'},
   {'link_title': 'DOMError',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/DOMError'},
   {'link_title': 'DOMException',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/DOMException'},
   {'link_title': 'DOMImplementation',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation'},
   {'link_title': 'DOMParser',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/DOMParser'},
   {'link_title': 'DOMPoint',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/DOMPoint'},
   {'link_title': 'DOMPointReadOnly',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/DOMPointReadOnly'},
   {'link_title': 'DOMRect',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/DOMRect'},
   {'link_title': 'DOMTokenList',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList'},
   {'link_title': 'Document',
    'url': 'https://developer.mozilla.org/en-US/docs/Web/API/Document'},
   {'link_title': 'DocumentFragment',

## Get html content and write them as json specs

In [5]:
# d = json.dumps(["hello"]).encode("ascii")
# s = base64.b64encode(d)
# f1 = open("f", "w")
# f1.write(str(s))
# f1.close()
# f2 = open("f", "r")
# a = f2.read()
# f2.close()
# # a = s.decode("utf8")
# l = json.loads(base64.b64decode(s).decode("ascii"))
# l[0][0]

In [6]:
# content = get_sections_content(sections_urls[0:4])
# write_specs(FILE_ROOT, "window", content)

## Pull from specs and parse

In [7]:
soups = load_soups(FILE_ROOT, "window.b64")

In [8]:
print(soups[0]["section_items"][0]["soup"].find("article").prettify())

<article class="main-page-content" lang="en-US">
 <header>
  <h1>
   Window: caches property
  </h1>
 </header>
 <div class="section-content">
  <div class="notecard secure" id="sect1">
   <p>
    <strong>
     Secure context:
    </strong>
    This feature is available only in
    <a href="/en-US/docs/Web/Security/Secure_Contexts">
     secure contexts
    </a>
    (HTTPS), in some or all
    <a href="#browser_compatibility">
     supporting browsers
    </a>
    .
   </p>
  </div>
  <p>
   The
   <strong>
    <code>
     caches
    </code>
   </strong>
   read-only property of the
   <a href="/en-US/docs/Web/API/Window">
    <code>
     Window
    </code>
   </a>
   interface returns the
   <a href="/en-US/docs/Web/API/CacheStorage">
    <code>
     CacheStorage
    </code>
   </a>
   object associated with the current context.
  This object enables functionality such as storing assets for offline use, and generating custom responses to requests.
  </p>
 </div>
 <section aria-labelledby="value">
  <h2 id="value">
   <a href="#value">
    Value
   </a>
  </h2>
  <div class="section-content">
   <p>
    A
    <a href="/en-US/docs/Web/API/CacheStorage">
     <code>
      CacheStorage
     </code>
    </a>
    object.
   </p>
  </div>
 </section>
 <section aria-labelledby="examples">
  <h2 id="examples">
   <a href="#examples">
    Examples
   </a>
  </h2>
  <div class="section-content">
   <p>
    The following example shows how a window can retrieve cached data.
   </p>
   <div class="code-example">
    <div class="example-header">
     <span class="language-name">
      js
     </span>
    </div>
    <pre class="brush: js notranslate" data-signature="3G0U9+xNOk0/vhqsDb2Rn3DxTcUnDeCg1uKVd37hvDI="><code>window<span class="token punctuation">.</span>caches<span class="token punctuation">.</span><span class="token function">open</span><span class="token punctuation">(</span><span class="token string">"v1"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">cache</span><span class="token punctuation">)</span> <span class="token operator">=&gt;</span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> cache<span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span><span class="token string">"/list"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre>
   </div>
  </div>
 </section>
 <h2 id="specifications">
  <a href="#specifications">
   Specifications
  </a>
 </h2>
 <table class="standard-table">
  <thead>
   <tr>
    <th scope="col">
     Specification
    </th>
   </tr>
  </thead>
  <tbody>
   <tr>
    <td>
     <a href="https://w3c.github.io/ServiceWorker/#self-caches">
      Service Workers
      <!-- -->
      <br/>
      <small>
       #
       <!-- -->
       self-caches
      </small>
     </a>
    </td>
   </tr>
  </tbody>
 </table>
 <h2 id="browser_compatibility">
  <a href="#browser_compatibility">
   Browser compatibility
  </a>
 </h2>
 <p>
  BCD tables only load in the browser
  <noscript>
   <!-- -->
   with JavaScript enabled. Enable JavaScript to view data.
  </noscript>
 </p>
 <section aria-labelledby="see_also">
  <h2 id="see_also">
   <a href="#see_also">
    See also
   </a>
  </h2>
  <div class="section-content">
   <ul>
    <li>
     <a href="/en-US/docs/Web/API/Service_Worker_API">
      Service Workers
     </a>
    </li>
    <li>
     <a href="/en-US/docs/Web/API/CacheStorage">
      <code>
       CacheStorage
      </code>
     </a>
    </li>
    <li>
     <a href="/en-US/docs/Web/API/Cache">
      <code>
       Cache
      </code>
     </a>
    </li>
   </ul>
  </div>
 </section>
</article>

In [9]:
df = produce_df(ROOT, soups)
df

,front,back,tags
0,Window: caches property,"<article class=""main-page-content"" lang=""en-US...",Browser Mdn InstanceProperties Caches Forward
1,Window: closed property,"<article class=""main-page-content"" lang=""en-US...",Browser Mdn InstanceProperties Closed Forward
2,Window: console property,"<article class=""main-page-content"" lang=""en-US...",Browser Mdn InstanceProperties Console Forward
3,Window: cookieStore property,"<article class=""main-page-content"" lang=""en-US...",Browser Mdn InstanceProperties Cookiestore For...
4,Window: credentialless property,"<article class=""main-page-content"" lang=""en-US...",Browser Mdn InstanceProperties Credentialless ...
...,...,...,...
299,The <strong><code>___</code></strong> event of...,"<article class=""main-page-content"" lang=""en-US...",Browser Mdn Events Vrdisplayconnect Forward
300,The <strong><code>___</code></strong> event of...,"<article class=""main-page-content"" lang=""en-US...",Browser Mdn Events Vrdisplaydeactivate Forward
301,The <strong><code>___</code></strong> event of...,"<article class=""main-page-content"" lang=""en-US...",Browser Mdn Events Vrdisplaydisconnect Forward
302,The <strong><code>___</code></strong> event of...,"<article class=""main-page-content"" lang=""en-US...",Browser Mdn Events Vrdisplaypresentchange Forward
303,The <strong><code>___</code></strong> interfac...,"<article class=""main-page-content"" lang=""en-US...",Browser Mdn Inheritance Eventtarget Forward

In [10]:
print(df["back"][0])

<article class="main-page-content" lang="en-US">
 <header>
  <h1>
   Window: caches property
  </h1>
 </header>
 <div class="section-content">
  <div class="notecard secure" id="sect1">
   <p>
    <strong>
     Secure context:
    </strong>
    This feature is available only in
    <a href="https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts">
     secure contexts
    </a>
    (HTTPS), in some or all
    <a href="#browser_compatibility">
     supporting browsers
    </a>
    .
   </p>
  </div>
  <p>
   The
   <strong>
    <code>
     caches
    </code>
   </strong>
   read-only property of the
   <a href="https://developer.mozilla.org/en-US/docs/Web/API/Window">
    <code>
     Window
    </code>
   </a>
   interface returns the
   <a href="https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage">
    <code>
     CacheStorage
    </code>
   </a>
   object associated with the current context.
  This object enables functionality such as storing assets for offline use, and generating custom responses to requests.
  </p>
 </div>
 <section aria-labelledby="value">
  <h2 id="value">
   <a href="#value">
    Value
   </a>
  </h2>
  <div class="section-content">
   <p>
    A
    <a href="https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage">
     <code>
      CacheStorage
     </code>
    </a>
    object.
   </p>
  </div>
 </section>
 <section aria-labelledby="examples">
  <h2 id="examples">
   <a href="#examples">
    Examples
   </a>
  </h2>
  <div class="section-content">
   <p>
    The following example shows how a window can retrieve cached data.
   </p>
   <div class="code-example">
    <div class="example-header">
     <span class="language-name">
      js
     </span>
    </div>
    <pre class="brush: js notranslate" data-signature="3G0U9+xNOk0/vhqsDb2Rn3DxTcUnDeCg1uKVd37hvDI="><code>window<span class="token punctuation">.</span>caches<span class="token punctuation">.</span><span class="token function">open</span><span class="token punctuation">(</span><span class="token string">"v1"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">cache</span><span class="token punctuation">)</span> <span class="token operator">=&gt;</span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> cache<span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span><span class="token string">"/list"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre>
   </div>
  </div>
 </section>
 <h2 id="specifications">
  <a href="#specifications">
   Specifications
  </a>
 </h2>
 <table class="standard-table" style=";width: 100%;">
  <thead>
   <tr>
    <th scope="col">
     Specification
    </th>
   </tr>
  </thead>
  <tbody>
   <tr>
    <td>
     <a href="https://w3c.github.io/ServiceWorker/#self-caches">
      Service Workers
      <!-- -->
      <br/>
      <small>
       #
       <!-- -->
       self-caches
      </small>
     </a>
    </td>
   </tr>
  </tbody>
 </table>
 <section aria-labelledby="see_also">
  <h2 id="see_also">
   <a href="#see_also">
    See also
   </a>
  </h2>
  <div class="section-content">
   <ul>
    <li>
     <a href="https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API">
      Service Workers
     </a>
    </li>
    <li>
     <a href="https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage">
      <code>
       CacheStorage
      </code>
     </a>
    </li>
    <li>
     <a href="https://developer.mozilla.org/en-US/docs/Web/API/Cache">
      <code>
       Cache
      </code>
     </a>
    </li>
   </ul>
  </div>
 </section>
 <hr/>
 <a href="https://developer.mozilla.org/en-US/docs/Web/API/Window/caches" id="inserted-mdn-link">
  Mdn entry for "caches"
 </a>
 <br/>
 <br/>
 <br/>
</article>

In [11]:
df[df["front"].str.contains(" Window.")]

,front,back,tags
209,The <code>___</code> read-only property of the...,"<article class=""main-page-content"" lang=""en-US...",Browser Mdn InstanceProperties Speechsynthesis...

In [12]:
df.to_csv(
    f"{ARTIFACTS_ROOT}/mdn/window-api.csv",
    header=False,
    encoding="utf-8",
    sep=";",
    index=False,
)