# Excel functions

In [60]:
import requests
import pandas as pd
from IPython.display import display
from IPython.core.display import HTML
from os import path
from bs4 import BeautifulSoup, NavigableString
from time import sleep
from pathlib import Path
from copy import deepcopy
import re

ROOT_URL = "https://support.microsoft.com"
ROOT_URI = f"{ROOT_URL}/en-us/office"
MAIN_URL = f"{ROOT_URI}/excel-functions-alphabetical-b3944572-255d-4efb-bb96-c6d90033e188"

OPTIONS = [
    "display.max_rows",
    None,
    "display.max_columns",
    "display.max_colwidth",
    None,
]
ROOT_ABSPATH = "/utkusarioglu-com/workshops/backtesting-workshop"
assets_abspath = path.join(ROOT_ABSPATH, "assets/excel")
artifacts_abspath = path.join(ROOT_ABSPATH, "artifacts/excel")
subpages_abspath = path.join(artifacts_abspath, "subpages")
source_abspath = path.join(assets_abspath, "index.html")
retrieved_abspath = path.join(artifacts_abspath, "retrieved.txt")
failed_abspath = path.join(artifacts_abspath, "failed.txt")
target_abspath = path.join(artifacts_abspath, "functions.csv")

In [10]:
# Get main file


def fetch_main_page():
    response = requests.get(MAIN_URL)
    if response.status_code != 200:
        raise RuntimeError("FETCH_FAIL")
    with open(source_abspath, "w") as f:
        f.write(response.text)


# fetch_main_page()

In [11]:
html = open(source_abspath, "r").read()
html

'\n<!DOCTYPE html>\n<html lang="en-US" dir="ltr">\n<head>\n\t<meta charset="utf-8" />\n\t<meta name="viewport" content="width=device-width, initial-scale=1.0" />\n\t<title>Excel functions (alphabetical) - Microsoft Support</title>\n\t\n\t\n\t\t<link rel="canonical" href="https://support.microsoft.com/en-us/office/excel-functions-alphabetical-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\n\t\t\t<link rel="alternate" hreflang="ar-SA" href="https://support.microsoft.com/ar-sa/office/%D8%AF%D8%A7%D9%84%D8%A7%D8%AA-excel-%D8%A8%D8%A7%D9%84%D8%AA%D8%B1%D8%AA%D9%8A%D8%A8-%D8%A7%D9%84%D8%A3%D8%A8%D8%AC%D8%AF%D9%8A-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="bg-BG" href="https://support.microsoft.com/bg-bg/office/%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8-%D0%BD%D0%B0-excel-%D0%BF%D0%BE-%D0%B0%D0%B7%D0%B1%D1%83%D1%87%D0%B5%D0%BD-%D1%80%D0%B5%D0%B4-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="cs-CZ" href="https://support.microsoft.com/cs-cz/office/funkce-excelu-podle-abecedy-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="da-DK" href="https://support.microsoft.com/da-dk/office/excel-funktioner-alfabetisk-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="de-DE" href="https://support.microsoft.com/de-de/office/excel-funktionen-alphabetisch-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="el-GR" href="https://support.microsoft.com/el-gr/office/%CF%83%CF%85%CE%BD%CE%B1%CF%81%CF%84%CE%AE%CF%83%CE%B5%CE%B9%CF%82-%CF%84%CE%BF%CF%85-excel-%CE%B1%CE%BB%CF%86%CE%B1%CE%B2%CE%B7%CF%84%CE%B9%CE%BA%CE%AC-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="en-AU" href="https://support.microsoft.com/en-au/office/excel-functions-alphabetical-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="en-GB" href="https://support.microsoft.com/en-gb/office/excel-functions-alphabetical-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="en-US" href="https://support.microsoft.com/en-us/office/excel-functions-alphabetical-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t\t<link rel="alternate" hreflang="x-default" href="https://support.microsoft.com/en-us/office/excel-functions-alphabetical-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="es-ES" href="https://support.microsoft.com/es-es/office/funciones-de-excel-por-orden-alfab%C3%A9tico-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="et-EE" href="https://support.microsoft.com/et-ee/office/exceli-funktsioonid-t%C3%A4hestikuliselt-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="fi-FI" href="https://support.microsoft.com/fi-fi/office/excelin-funktiot-aakkosj%C3%A4rjestyksess%C3%A4-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="fr-FR" href="https://support.microsoft.com/fr-fr/office/fonctions-excel-par-ordre-alphab%C3%A9tique-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="he-IL" href="https://support.microsoft.com/he-il/office/%D7%A4%D7%95%D7%A0%D7%A7%D7%A6%D7%99%D7%95%D7%AA-%D7%A9%D7%9C-excel-%D7%91%D7%A1%D7%93%D7%A8-%D7%90%D7%9C%D7%A4%D7%91%D7%99%D7%AA%D7%99-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="hr-HR" href="https://support.microsoft.com/hr-hr/office/funkcije-programa-excel-abecednim-redoslijedom-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="hu-HU" href="https://support.microsoft.com/hu-hu/office/az-excel-f%C3%BCggv%C3%A9nyeinek-bet%C5%B1rendes-list%C3%A1ja-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="id-ID" href="https://support.microsoft.com/id-id/office/fungsi-excel-menurut-abjad-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="it-IT" href="https://support.microsoft.com/it-it/office/funzioni-di-excel-in-ordine-alfabetico-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="ja-JP" href="https://support.microsoft.com/ja-jp/office/excel-%E9%96%A2%E6%95%B0-%E3%82%A2%E3%83%AB%E3%83%95%E3%82%A1%E3%83%99%E3%83%83%E3%83%88%E9%A0%86-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="ko-KR" href="https://support.microsoft.com/ko-kr/office/excel-%ED%95%A8%EC%88%98-%EC%82%AC%EC%A0%84%EC%88%9C-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="lt-LT" href="https://support.microsoft.com/lt-lt/office/-excel-funkcijos-pagal-ab%C4%97c%C4%97l%C4%99-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="lv-LV" href="https://support.microsoft.com/lv-lv/office/excel-funkciju-saraksts-p%C4%93c-alfab%C4%93ta-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="nb-NO" href="https://support.microsoft.com/nb-no/office/funksjoner-i-excel-alfabetisk-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="nl-NL" href="https://support.microsoft.com/nl-nl/office/excel-functies-alfabetisch-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="pl-PL" href="https://support.microsoft.com/pl-pl/office/funkcje-programu-excel-lista-alfabetyczna-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="pt-BR" href="https://support.microsoft.com/pt-br/office/fun%C3%A7%C3%B5es-do-excel-ordem-alfab%C3%A9tica-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="pt-PT" href="https://support.microsoft.com/pt-pt/office/fun%C3%A7%C3%B5es-do-excel-por-ordem-alfab%C3%A9tica-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="ro-RO" href="https://support.microsoft.com/ro-ro/office/func%C8%9Bii-excel-%C3%AEn-ordine-alfabetic%C4%83-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="ru-RU" href="https://support.microsoft.com/ru-ru/office/%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8-excel-%D0%BF%D0%BE-%D0%B0%D0%BB%D1%84%D0%B0%D0%B2%D0%B8%D1%82%D1%83-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="sk-SK" href="https://support.microsoft.com/sk-sk/office/zoznam-funkci%C3%AD-excelu-pod%C4%BEa-abecedy-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="sl-SI" href="https://support.microsoft.com/sl-si/office/funkcije-v-excelu-po-abecedi-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="sr-Latn-RS" href="https://support.microsoft.com/sr-latn-rs/office/excel-funkcije-po-abecedi-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="sv-SE" href="https://support.microsoft.com/sv-se/office/excel-funktioner-alfabetisk-ordning-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="th-TH" href="https://support.microsoft.com/th-th/office/%E0%B8%9F%E0%B8%B1%E0%B8%87%E0%B8%81%E0%B9%8C%E0%B8%8A%E0%B8%B1%E0%B8%99%E0%B8%82%E0%B8%AD%E0%B8%87-excel-%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%87%E0%B8%A5%E0%B8%B3%E0%B8%94%E0%B8%B1%E0%B8%9A%E0%B8%95%E0%B8%B2%E0%B8%A1%E0%B8%95%E0%B8%B1%E0%B8%A7%E0%B8%AD%E0%B8%B1%E0%B8%81%E0%B8%A9%E0%B8%A3-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="tr-TR" href="https://support.microsoft.com/tr-tr/office/excel-i%C5%9Flevleri-alfabetik-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="uk-UA" href="https://support.microsoft.com/uk-ua/office/%D1%84%D1%83%D0%BD%D0%BA%D1%86%D1%96%D1%97-excel-%D0%B7%D0%B0-%D0%B0%D0%BB%D1%84%D0%B0%D0%B2%D1%96%D1%82%D0%BE%D0%BC-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="vi-VN" href="https://support.microsoft.com/vi-vn/office/c%C3%A1c-h%C3%A0m-excel-theo-th%C6%B0%CC%81-t%C6%B0%CC%A3-ba%CC%89ng-ch%C6%B0%CC%83-ca%CC%81i-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="zh-CN" href="https://support.microsoft.com/zh-cn/office/excel-%E5%87%BD%E6%95%B0-%E6%8C%89%E5%AD%97%E6%AF%8D%E9%A1%BA%E5%BA%8F-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="zh-HK" href="https://support.microsoft.com/zh-hk/office/excel-%E5%87%BD%E6%95%B8-%E4%BE%9D%E8%8B%B1%E6%96%87%E5%AD%97%E6%AF%8D%E9%A0%86%E5%BA%8F%E6%8E%92%E5%88%97-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\t\t<link rel="alternate" hreflang="zh-TW" href="https://support.microsoft.com/zh-tw/office/excel-%E5%87%BD%E6%95%B8-%E4%BE%9D%E8%8B%B1%E6%96%87%E5%AD%97%E6%AF%8D%E9%A0%86%E5%BA%8F%E6%8E%92%E5%88%97-b3944572-255d-4efb-bb96-c6d90033e188" />\n\t<meta name="awa-articleGuid" content="b3944572-255d-4efb-bb96-c6d90033e188" />\n\t\n\t<meta name="description" content="A complete list of all Excel functions in alphabetical order." />\n\t<meta name="firstPublishedDate" content="2014-05-20" />\n\t<meta name="lastPublishedDate" content="2024-04-19" />\n\t<meta name="commitId" content="69aac0e7a697c877564c807695a638a92f6f5158" />\n\t<meta name="schemaName" content="HELP ARTICLE" />\n\t<meta name="awa-schemaName" content="HELP ARTICLE" />\n\n\t<meta name="search.applicationSuite" content="Excel,Excel,Excel" />\n\t<meta name="search.appverid" content="ZXL160,ZXL190,MXL190,ZXL900,MXL900,WAE150,WAE140,ZXL210,MXL210,MXL240,ZXL240" />\n\t<meta name="search.audienceType" content="End User" />\n\t<meta name="search.contenttype" content="Reference" />\n\t\n\t<meta name="search.description" content="A complete list of all Excel functions in alphabetical order." />\n\t<meta name="search.IsOfficeDoc" content="true" />\n\t<meta name="search.OCMSasset" content="HA102753227" />\n\t\n\t\n\t\n\t\n\t<meta name="search.sku" content="Excel,Excel Online,Excel Web App" />\n\t<meta name="search.skuid" content="ZXL160,WAE150,WAE140" />\n\t<meta name="search.softwareVersion" content="16,19,19,90,90,15,14,21,21,24,24" />\n\t<meta name="search.mkt" content="en-US" />\n\n\t\n\t\n\t<meta name="ms.lang" content="en" />\n\t<meta name="ms.loc" content="US" />\n\t<meta name="ms.ocpub.assetID" content="b3944572-255d-4efb-bb96-c6d90033e188" />\n\n\t\n\t<meta name="awa-isContactUsAllowed" content="false" />\n\t<meta name="awa-asst" content="b3944572-255d-4efb-bb96-c6d90033e188" />\n\t<meta name="awa-pageType" content="Article" />\n\t\n\n\t\n\n\n<meta name="awa-env" content="Production" />\n<meta name="awa-market" content="en-US" />\n<meta name="awa-contentlang" content="en" />\n<meta name="awa-userFlightingId" content="689c0a72-a4e4-4256-8fac-f3a5c44d6443" />\n<meta name="awa-expid" content="P-E-1289286-3-5;P-E-1288695-17-5;P-E-1288693-C1-6;P-E-1288715-11-5;P-E-1288712-9-5;P-E-1288690-C1-5;P-E-1260007-C1-3;P-E-1247614-2-8;P-E-1046152-2-3;P-R-1245128-2-4;P-R-1235984-2-3;P-R-1211158-1-4;P-R-1150391-2-8;P-R-1150395-2-8;P-R-1150399-2-8;P-R-1150396-2-8;P-R-1150394-2-8;P-R-1150390-2-8;P-R-1150386-2-8;P-R-1146801-1-11;P-R-1141562-1-2;P-R-1141283-2-9;P-R-1136354-4-8;P-R-1119659-1-16;P-R-1119437-1-17;P-R-1116805-2-18;P-R-1116803-2-20;P-R-1114100-1-2;P-R-1100996-2-14;P-R-1096341-2-6;P-R-1089468-1-2;P-R-1085248-1-2;P-R-1072011-6-8;P-R-1033854-4-6;P-R-1029969-4-4;P-R-1020735-1-10;P-R-1018544-4-7;P-R-1009708-2-9;P-R-1005895-2-11;P-R-116475-1-23;P-R-113175-4-7;P-R-113174-1-2;P-R-110379-1-7;P-R-107838-1-7;P-R-106524-1-3;P-R-103787-2-5;P-R-101783-1-2;P-R-97577-1-5;P-R-97457-1-10;P-R-94390-1-2;P-R-94360-10-25;P-R-93416-1-3;P-R-90963-2-2;P-R-85265-4-8;P-R-73296-2-15" />\n<meta name="awa-irisId" />\n<meta name="awa-origindatacenter" content="France Central" />\n<meta name="awa-variationid" content="ECS" />\n<meta name="awa-prdct" content="office.com" />\n<meta name="awa-stv" content="2.0.3-43d7e6d136f8437be4a3605eb0069da3e25f4bad" />\n\n\n \n\t<meta name="awa-title" content="Excel functions (alphabetical) - Microsoft Support" />\n\t\n\t<meta name="awa-selfHelpExp" content="railbanner_business" />\n\t<meta name="awa-dataBoundary" content="WW" />\n\n\t<link rel="stylesheet" href="/css/fonts/site-fonts.css?v=4M_1wOASateOs9zdphCtIqMvtKo366Gf6pkOjDqzkYo" />\n\t<link rel="stylesheet" href="/css/glyphs/glyphs.css?v=N9jMfMIoO_s7OATN0j5LYqmO9MCqHDjfpaUV2RuaEy8" />\n\n\t<link rel="preconnect" href="https://browser.events.data.microsoft.com" />\n\t<link rel="preconnect" href="https://c.s-microsoft.com" />\n\t<link rel="preconnect" href="https://js.monitor.azure.com" />\n\t<link rel="preconnect" href="https://login.live.com" />\n\t<link rel="preconnect" href="https://login.microsoftonline.com" />\n\t<link rel="preconnect" href="https://mem.gfx.ms" />\n\t<link rel="preconnect" href="https://www.microsoft.com" />\n\n\t<link rel="stylesheet" href="/css/Article/css.css?v=Z6ZkkY_X8iTM42LbcHhEDNaT4e9rMO_zPAbxEsFxAvo" />\n\t<link rel="stylesheet" href="/css/Article/article.css?v=K8zWgnTQR4bpKdNsUEWPie7jCayl_RhEnBw5fiPiYzQ" />\n\t\n\t<link rel="stylesheet" href="/css/SearchBox/search-box.css?v=bybwzGBajHicVXspVs540UfV0swW0vCbOmBjBryj9N4" />\n\t<link rel="stylesheet" href="/css/sitewide/articleCss-overwrite.css?v=D0lQRoIlvFHSQBRTb-gAQ5KkFe8B8NuSoliBjnT5xZ4" />\n\t\n\t\n\t<link rel="stylesheet" href="/css/MeControlCallout/teaching-callout.css?v=690pjf05o15fVEafEpUwgaF8vqVfOkp5wP1Jl9gE99U" />\n\t\n\n\t\n\t<link rel="stylesheet" href="/css/promotionbanner/promotion-banner.css?v=cAmflE3c6Gw7niTOiMPEie9MY87yDE2mSl3DO7_jZRI" media="none" onload="this.media=&#x27;all&#x27;" /><noscript><link href="/css/promotionbanner/promotion-banner.css?v=cAmflE3c6Gw7niTOiMPEie9MY87yDE2mSl3DO7_jZRI" rel="stylesheet"></noscript>\n\t\n\t<link rel="stylesheet" href="/css/ArticleSupportBridge/article-support-bridge.css?v=R_P0TJvD9HoRHQBEdvBR1WhNn7dSbvOYWmVA9taxbpM" media="none" onload="this.media=&#x27;all&#x27;" /><noscript><link href="/css/ArticleSupportBridge/article-support-bridge.css?v=R_P0TJvD9HoRHQBEdvBR1WhNn7dSbvOYWmVA9taxbpM" rel="stylesheet"></noscript>\n\n\t<link rel="stylesheet" href="/css/StickyFeedback/sticky-feedback.css?v=cMfNdAUue7NxZUj3dIt_v5DIuzmw9ohJW109iXQpWnI" media="none" onload="this.media=&#x27;all&#x27;" /><noscript><link href="/css/StickyFeedback/sticky-feedback.css?v=cMfNdAUue7NxZUj3dIt_v5DIuzmw9ohJW109iXQpWnI" rel="stylesheet"></noscript>\n\t<link rel="stylesheet" href="/css/feedback/feedback.css?v=Rkcw_yfLWOMtOcWOljMOiZgymMcrG0GDpo4Lf-TUzPo" media="none" onload="this.media=&#x27;all&#x27;" /><noscript><link href="/css/feedback/feedback.css?v=Rkcw_yfLWOMtOcWOljMOiZgymMcrG0GDpo4Lf-TUzPo" rel="stylesheet"></noscript>\n\n\t\n\t\n\n\t<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">\n<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">\n<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">\n\n\n\t\n        <link rel="stylesheet" href="https://www.microsoft.com/onerfstatics/marketingsites-neu-prod/west-european/shell/_scrf/css/themes=default.device=uplevel_web_pc/1b-9d8ed9/c9-be0100/a6-e969ef/43-9f2e7c/82-8b5456/a0-5d3913/43-5a5ab8/ca-ae3ce4?ver=2.0&amp;_cf=02242021_3231" type="text/css" media="all" />\n    \n\n\t\n\t\n\t<script type="text/javascript">\n\t\tvar OOGlobal = {\n\t\t\tBaseDomain: location.protocol + "//" + location.host,\n\t\t\tCulture: "en-US",\n\t\t\tLanguage: "en",\n\t\t\tLCID: "1033",\n\t\t\tIsAuthenticated: "False",\n\t\t\tWebAppUrl: "https://office.com/start",\n\t\t\tGUID: "b3944572-255d-4efb-bb96-c6d90033e188",\n\t\t\tPlatform: navigator.platform,\n\t\t\tMixOembedUrl: "https://mix.office.com/oembed/",\n\t\t\tMixWatchUrl: "https://mix.office.com/watch/"\n\t\t};\n\t</script>\n\n\t\n\t\t\n\n\n\n\n\n\t<script type="text/javascript">\n\t\t(function () {\n\t\t\tvar creativeReady = false;\n\t\t\tvar isSilentSignInComplete = false;\n\t\t\tvar authInfo = {\n\t\t\t\tauthType: "None",\n\t\t\t\tpuid: "",\n\t\t\t\ttenantId: "",\n\t\t\t\tisAdult: true\n\t\t\t\t};\n\n\t\t\tvar renderPromotion = function (dataBoundary) {\n\t\t\t\tif (creativeReady && isSilentSignInComplete) {\n\t\t\t\t\twindow.UcsCreative.renderTemplate({\n\t\t\t\t\t\tpartnerId: "7bb7e07d-3e57-4ee3-b78f-26a4292b841a",\n\t\t\t\t\t\tshouldSetUcsMuid: false,\n\t\t\t\t\t\tdataBoundary: dataBoundary,\n\t\t\t\t\t\tattributes: {\n\t\t\t\t\t\t\tplacement: "88000534",\n\t\t\t\t\t\t\tlocale: "en-us",\n\t\t\t\t\t\t\tcountry: "us",\n\t\t\t\t\t\t\tscs_ecsFlightId: "P-E-1289286-3;P-E-1288695-17;P-E-1288693-C1;P-E-1288715-11;P-E-1288712-9;P-E-1288690-C1;P-E-1260007-C1;P-E-1247614-2;P-E-1046152-2;P-R-1245128-2;P-R-1235984-2;P-R-1211158-1;P-R-1150391-2;P-R-1150395-2;P-R-1150399-2;P-R-1150396-2;P-R-1150394-2;P-R-1150390-2;P-R-1150386-2;P-R-1146801-1;P-R-1141562-1;P-R-1141283-2;P-R-1136354-4;P-R-1119659-1;P-R-1119437-1;P-R-1116805-2;P-R-1116803-2;P-R-1114100-1;P-R-1100996-2;P-R-1096341-2;P-R-1089468-1;P-R-1085248-1;P-R-1072011-6;P-R-1033854-4;P-R-1029969-4;P-R-1020735-1;P-R-1018544-4;P-R-1009708-2;P-R-1005895-2;P-R-116475-1;P-R-113175-4;P-R-113174-1;P-R-110379-1;P-R-107838-1;P-R-106524-1;P-R-103787-2;P-R-101783-1;P-R-97577-1;P-R-97457-1;P-R-94390-1;P-R-94360-10;P-R-93416-1;P-R-90963-2;P-R-85265-4;P-R-73296-2",\n\t\t\t\t\t\t\tSCS_promotionCategory: "uhfbuybutton;railbanner_business",\n\t\t\t\t\t\t\tarticleType: "railbanner_business",\n\t\t\t\t\t\t\toperatingSystem: "",\n\t\t\t\t\t\t\tauthType: authInfo.authType,\n\t\t\t\t\t\t\tPUID: authInfo.puid,\n\t\t\t\t\t\t\tTenantId: authInfo.tenantId,\n\t\t\t\t\t\t\tTOPT: "",\n\t\t\t\t\t\t\tAdditionalBannerId: "ucsRailInlineContainer",\n\t\t\t\t\t\t}\n\t\t\t\t\t});\n\t\t\t\t}\n\t\t\t};\n\n\t\t\twindow.document.addEventListener(\'ucsCreativeRendered\', function () {\n\t\t\t\tif (typeof window.initPromotionLogger !== \'undefined\') {\n\t\t\t\t\twindow.initPromotionLogger();\n\t\t\t\t}\n\t\t\t});\n\n\t\t\twindow.document.addEventListener(\'ucsCreativeReady\', function () {\n\t\t\t\tcreativeReady = true;\n\t\t\t\trenderPromotion("WW");\n\t\t\t});\n\n\t\t\tif (!isSilentSignInComplete) {\n\t\t\t\twindow.document.addEventListener(\'silentSignInComplete\', function (event) {\n\t\t\t\t\tif (event.detail && event.detail.puid) {\n\t\t\t\t\t\tauthInfo.isAdult = event.detail.isAdult;\n\t\t\t\t\t\tauthInfo.authType = event.detail.authType;\n\t\t\t\t\t\tauthInfo.puid = event.detail.puid;\n\t\t\t\t\t\tauthInfo.tenantId = event.detail.account.tenantId;\n\t\t\t\t\t}\n\n\t\t\t\t\tisSilentSignInComplete = true;\n\t\t\t\t\trenderPromotion(event.detail.dataBoundary);\n\t\t\t\t});\n\t\t\t}\n\t\t})();\n\t</script>\n\n\n\n<script type="text/javascript" defer src="/lib/ucs/dist/ucsCreativeService.js?v=Xoy5TlH5ODlsYqqzeOnM642UwAhzAIQYiqwgfoFRaX4"></script>\n\t\n\n\t<script>\n\t\tif (window.location.search) {\n\t\t\tvar params = new URLSearchParams(window.location.search);\n\t\t\tif (params.has(\'action\') && params.get(\'action\') === \'download\'){\n\t\t\t\tparams.delete(\'action\');\n\t\t\t}\n\n\t\t\thistory.replaceState({}, \'\', window.location.pathname + (params.toString() ? \'?\' + params.toString() : \'\'));\n\t\t}\n\t</script>\n\n\n</head>\n<body class="supCont ocArticle">\n\t<div id="ocBodyWrapper">\n\t\t\n\n\t\t<div class="ucsUhfContainer"></div>\n\n\t\t\n            <div id="headerArea" class="uhf"  data-m=\'{"cN":"headerArea","cT":"Area_coreuiArea","id":"a1Body","sN":1,"aN":"Body"}\'>\n                <div id="headerRegion"      data-region-key="headerregion" data-m=\'{"cN":"headerRegion","cT":"Region_coreui-region","id":"r1a1","sN":1,"aN":"a1"}\' >\n\n    <div  id="headerUniversalHeader" data-m=\'{"cN":"headerUniversalHeader","cT":"Module_coreui-universalheader","id":"m1r1a1","sN":1,"aN":"r1a1"}\'  data-module-id="Category|headerRegion|coreui-region|headerUniversalHeader|coreui-universalheader">\n        \n\n\n\n\n\n\n        <a id="uhfSkipToMain" class="m-skip-to-main" href="javascript:void(0)" data-href="#ocHelp" tabindex="0" data-m=\'{"cN":"Skip to content_nonnav","id":"nn1m1r1a1","sN":1,"aN":"m1r1a1"}\'>Skip to main content</a>\n\n\n<header class="c-uhfh context-uhf no-js c-sgl-stck c-category-header " itemscope="itemscope" data-header-footprint="/SMCConvergence/ContextualHeader-Microsoft365, fromServ

In [76]:
def fetch_pages(html):
    soup = BeautifulSoup(html, "html.parser")
    table = soup.table
    anchors = table.find_all("a")
    retrieved = []
    failed = []
    print(f"Retrieving {len(anchors)} entries")
    for anchor in anchors:
        url = ROOT_URL + anchor["href"]
        filename = url.rsplit("/", 1)[-1] + ".html"
        response = requests.get(url)
        if response.status_code != 200:
            print(f"Failed: {url}", response.status_code)
            failed.append(f"{url} {response.status_code}")
            continue
        with open(path.join(subpages_abspath, filename), "w") as f:
            f.write(response.text)
        retrieved.append(url)
        print(f"Retrieved: {filename}")
        sleep(0.5)

    with open(retrieved_abspath, "w") as f:
        f.write("\n".join(retrieved))
    with open(failed_abspath, "w") as f:
        f.write("\n".join(failed))


# fetch_pages()

In [56]:
# Process soups
def replace_function_name(nav_string, title_text):
    if isinstance(nav_string, NavigableString):
        replacement = nav_string.replace(title_text, "___")
        nav_string.replace_with(replacement)


def process_soup(html):
    soup = BeautifulSoup(html, "html.parser")
    title_text = soup.h1.text.rsplit(" ", 1)[0].strip()
    title_h2_soup = BeautifulSoup(f"<h2>{title_text}</h2>", "html.parser")
    title_p_soup = BeautifulSoup(f"<p>{title_text}</p>", "html.parser")
    sections = soup.article.find_all("section")
    description_soup = None
    syntax_soup = None
    remarks_soup = None
    examples_soup = None
    for section in sections:
        if section.h2 is not None:
            if section.h2.text == "Description":
                description_soup = section
            if section.h2.text == "Syntax":
                syntax_soup = section
            if section.h2.text == "Remarks":
                remarks_soup = section
            if section.h2.text == "Examples":
                examples_soup = section
    if description_soup is None:
        description_soup = sections[0]

    # Description corrections
    if description_soup.h2 is not None:
        description_soup.h2.decompose()

    sup_arg_row = description_soup.find(class_="supARG-row")
    if sup_arg_row is not None:
        sup_arg_row.decompose()

    ocp_video = description_soup.find(class_="ocpVideo")
    if ocp_video is not None:
        ocp_video.decompose()

    anchors = description_soup.find_all("a")
    for anchor in anchors:
        slash_start = anchor["href"].startswith("/")
        hash_start = anchor["href"].startswith("#")
        if slash_start or hash_start:
            anchor["href"] = ROOT_URL + anchor["href"]

    # Summary corrections
    summary_text_raw = description_soup.find("p").text
    summary_text_arr = summary_text_raw.split(". ")
    if len(summary_text_arr) > 1:
        summary_text = summary_text_arr[0] + "."
    else:
        summary_text = summary_text_arr[0]
    sorted_title_text = [e.strip() for e in sorted(title_text.split(","))]
    sorted_title_text = sorted(sorted_title_text, key=len, reverse=True)
    for part in sorted_title_text:
        summary_text = re.sub(part, "___", summary_text)
    summary_soup = BeautifulSoup(f"<p>{summary_text}</p>", "html.parser")

    combined_description = BeautifulSoup(
        "".join(
            [
                item.prettify()
                for item in [
                    title_h2_soup,
                    description_soup,
                    syntax_soup,
                    examples_soup,
                    remarks_soup,
                ]
                if item is not None
            ]
        ),
        "html.parser",
    )

    return {
        "title_text": title_text,
        "title_h2_soup": title_h2_soup,
        "title_p_soup": title_p_soup,
        "description_soup": description_soup,
        "syntax_soup": syntax_soup,
        "remarks_soup": remarks_soup,
        "examples_soup": examples_soup,
        "summary_soup": summary_soup,
        "has_description": description_soup is not None,
        "has_syntax": syntax_soup is not None,
        "has_remarks": remarks_soup is not None,
        "has_examples": examples_soup is not None,
        "has_summary": summary_soup is not None,
        "combined_description_soup": combined_description,
    }


def soup_generator():
    files = [f for f in Path(subpages_abspath).iterdir() if f.is_file()]
    for f in files:
        with open(f, "r") as f:
            html = f.read()
            yield process_soup(html)


entries = []
counter = 0
for props in soup_generator():
    counter += 1
    # if counter > 10:
    #     break
    tags = ["MicrosoftOffice-2021"]
    if props["has_examples"]:
        tags.append("ExcelHasExamples")
    if props["has_remarks"]:
        tags.append("ExcelHasRemarks")
    if props["has_syntax"]:
        tags.append("ExcelHasSyntax")
    entries.append(
        {
            "title_p_html": props["title_p_soup"].prettify(),
            "description_html": props["combined_description_soup"].prettify(),
            "summary_html": props["summary_soup"].prettify(),
            "tags": " ".join(tags),
        }
    )
    # traits = []
    # for key in props.keys():
    #     if "has_" in key:
    #         if not props[key]:
    #             traits.append(key)
    # if len(traits) > 0:
    #     print("-" * 40)
    #     print(
    #         props["title_text"],
    #         ", ".join([t.replace("has_", "") for t in traits]),
    #     )
    #     # display(HTML(props["summary_soup"].prettify()))
    #     display(HTML(props["combined_description_soup"].prettify()))
    #     # if props["has_examples"]:
    #     #     display(HTML(props["examples_soup"].prettify()))

print("Final counter:", counter)

Final counter: 491

In [53]:
for entry in entries:
    display(HTML(entry["title_p_html"]))
    display(HTML(entry["summary_html"]))
    display(HTML(entry["description_html"]))

In [57]:
df = pd.DataFrame(entries)
df.rename(
    columns={
        "title_p_html": "TitleHtml",
        "description_html": "DescriptionHtml",
        "summary_html": "SummaryHtml",
    },
    inplace=True,
)
df.head()

,TitleHtml,DescriptionHtml,SummaryHtml,tags
0,<p>\n CUBEKPIMEMBER\n</p>\n,<h2>\n CUBEKPIMEMBER\n</h2>\n<section aria-lab...,<p>\n Returns a key performance indicator (KPI...,MicrosoftOffice-2021 ExcelHasExamples ExcelHas...
1,<p>\n ERFC\n</p>\n,"<h2>\n ERFC\n</h2>\n<section aria-labelledby=""...",<p>\n Returns the complementary ERF function i...,MicrosoftOffice-2021 ExcelHasRemarks ExcelHasS...
2,<p>\n LARGE\n</p>\n,<h2>\n LARGE\n</h2>\n<section aria-labelledby=...,<p>\n Returns the k-th largest value in a data...,MicrosoftOffice-2021 ExcelHasRemarks ExcelHasS...
3,<p>\n NOT\n</p>\n,"<h2>\n NOT\n</h2>\n<section class=""ocpIntroduc...","<p>\n Use the ___ function, one of the logical...",MicrosoftOffice-2021 ExcelHasExamples
4,<p>\n BITRSHIFT\n</p>\n,<h2>\n BITRSHIFT\n</h2>\n<section aria-labelle...,<p>\n Returns a number shifted right by the sp...,MicrosoftOffice-2021 ExcelHasRemarks ExcelHasS...

In [63]:
df.sample(n=10)

,TitleHtml,DescriptionHtml,SummaryHtml,tags
30,<p>\n DATEVALUE\n</p>\n,<h2>\n DATEVALUE\n</h2>\n<section aria-labelle...,<p>\n The ___ function converts a date that is...,MicrosoftOffice-2021 ExcelHasRemarks ExcelHasS...
446,<p>\n NORMSDIST\n</p>\n,"<h2>\n NORMSDIST\n</h2>\n<section class=""ocpIn...",<p>\n Returns the standard normal cumulative d...,MicrosoftOffice-2021 ExcelHasRemarks ExcelHasS...
267,<p>\n MINIFS\n</p>\n,"<h2>\n MINIFS\n</h2>\n<section class=""ocpIntro...",<p>\n The ___ function returns the minimum val...,MicrosoftOffice-2021 ExcelHasExamples ExcelHas...
485,<p>\n ASC\n</p>\n,"<h2>\n ASC\n</h2>\n<section aria-labelledby=""I...",<p>\n For Double-byte character set (DBCS) lan...,MicrosoftOffice-2021 ExcelHasSyntax
78,<p>\n SUM\n</p>\n,"<h2>\n SUM\n</h2>\n<section class=""ocpIntroduc...",<p>\n The ___ function adds values.\n</p>\n,MicrosoftOffice-2021
118,<p>\n T.INV\n</p>\n,"<h2>\n T.INV\n</h2>\n<section class=""ocpIntrod...",<p>\n This article describes the formula synta...,MicrosoftOffice-2021 ExcelHasRemarks ExcelHasS...
288,<p>\n AVERAGEA\n</p>\n,<h2>\n AVERAGEA\n</h2>\n<section aria-labelled...,<p>\n Calculates the average (arithmetic mean)...,MicrosoftOffice-2021 ExcelHasRemarks ExcelHasS...
210,<p>\n N\n</p>\n,"<h2>\n N\n</h2>\n<section aria-labelledby=""ID0...",<p>\n Returns a value converted to a number.\n...,MicrosoftOffice-2021 ExcelHasRemarks ExcelHasS...
26,<p>\n COTH\n</p>\n,"<h2>\n COTH\n</h2>\n<section aria-labelledby=""...",<p>\n Return the hyperbolic cotangent of a hyp...,MicrosoftOffice-2021 ExcelHasRemarks ExcelHasS...
69,<p>\n NORMSINV\n</p>\n,"<h2>\n NORMSINV\n</h2>\n<section class=""ocpInt...",<p>\n Returns the inverse of the standard norm...,MicrosoftOffice-2021 ExcelHasRemarks ExcelHasS...

In [64]:
df.to_csv(target_abspath, sep="|", index=False, header=False)