In [14]:
import pandas as pd
from os.path import join, abspath
from bs4 import BeautifulSoup
from bs4.element import NavigableString
import numpy as np
from IPython.display import display

artifacts_abspath = abspath("../../../artifacts")
assets_abspath = abspath("../../../assets")
source_abspath = join(assets_abspath, "evm/opcodes.xlsx")
target_abspath = join(artifacts_abspath, "evm/anki_export.csv")

In [2]:
notes_remove = "(opens in a new tab)"
source = pd.read_excel(source_abspath, sheet_name="Sheet")
source.rename(
    columns={
        "Stack": "Opcode",
        "Name": "Mnemonic",
        "Initial Stack": "Inputs",
        "Resulting Stack": "Output",
    },
    inplace=True,
)
source["Notes"] = source["Notes"].apply(
    lambda v: v.replace(notes_remove, "") if not pd.isna(v) else v
)
source

,Opcode,Mnemonic,Gas Constant,Gas Dynamic,Inputs,Output,Mem / Storage,Notes
0,00,STOP,0,NaN,NaN,NaN,NaN,halt execution
1,01,ADD,3,NaN,"a, b",a + b,NaN,(u)int256 addition modulo 2**256
2,02,MUL,5,NaN,"a, b",a * b,NaN,(u)int256 multiplication modulo 2**256
3,03,SUB,3,NaN,"a, b",a - b,NaN,(u)int256 addition modulo 2**256
4,04,DIV,5,NaN,"a, b",a // b,NaN,uint256 division
...,...,...,...,...,...,...,...,...
151,FA,STATICCALL,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"gas, addr, argOst, argLen, retOst, retLen",success,mem[retOst:retOst+retLen-1] := returndata,NaN
152,FB-FC,invalid,NaN,NaN,NaN,NaN,NaN,NaN
153,FD,REVERT,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len",.,NaN,revert(mem[ost:ost+len-1])
154,FE,INVALID,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,NaN,NaN,NaN,designated invalid opcode - EIP-141
155,FF,SELFDESTRUCT,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,addr,.,NaN,sends all ETH to addr; if executed in the same...

In [4]:
def create_back(row):
    s = BeautifulSoup("", "html.parser")
    h2 = s.new_tag("h2")
    h2.string = f"{row['Mnemonic']} ({row['Opcode']})"

    dl = s.new_tag("dl", style="text-align: left;")
    dt_styles = "font-weight: bold;"

    if not pd.isna(row["Notes"]):
        notes_dt = s.new_tag("dt", style=dt_styles)
        notes_dt.append(NavigableString("Notes"))
        notes_dd = s.new_tag("dd")
        notes_dd.append(NavigableString(row["Notes"]))
        dl.append(notes_dt)
        dl.append(notes_dd)

    gas_dt = s.new_tag("dt", style=dt_styles)
    gas_dt.append(NavigableString("Gas"))
    gas_dd = s.new_tag("dd")
    if not pd.isna(row["Gas Constant"]):
        gas_dd.append(NavigableString(str(row["Gas Constant"])))
    if not pd.isna(row["Gas Dynamic"]):
        gas_dyn = s.new_tag("a", href=row["Gas Dynamic"])
        gas_dyn.string = "dynamic"
        if not pd.isna(row["Gas Constant"]):
            gas_dd.append(NavigableString(" + "))
        gas_dd.append(gas_dyn)
    if pd.isna(row["Gas Constant"]) and pd.isna(row["Gas Dynamic"]):
        gas_dd.append(NavigableString("0"))
    dl.append(gas_dt)
    dl.append(gas_dd)

    if not pd.isna(row["Inputs"]):
        inputs_dt = s.new_tag("dt", style=dt_styles)
        inputs_dt.append(NavigableString("Inputs"))
        inputs_dd = s.new_tag("dd")
        inputs_dd.append(NavigableString(row["Inputs"]))
        dl.append(inputs_dt)
        dl.append(inputs_dd)

    if not pd.isna(row["Output"]):
        outputs_dt = s.new_tag("dt", style=dt_styles)
        outputs_dt.append(NavigableString("Output"))
        outputs_dd = s.new_tag("dd")
        outputs_dd.append(NavigableString(row["Output"]))
        dl.append(outputs_dt)
        dl.append(outputs_dd)

    if not pd.isna(row["Mem / Storage"]):
        mem_dt = s.new_tag("dt", style=dt_styles)
        mem_dt.append(NavigableString("Mem / Storage"))
        mem_dd = s.new_tag("dd")
        mem_dd.append(NavigableString(row["Mem / Storage"]))
        dl.append(mem_dt)
        dl.append(mem_dd)

    s.append(h2)
    s.append(dl)
    return s.prettify()

In [15]:
df = source.copy()
df["Back"] = df.apply(create_back, axis=1)
with pd.option_context("display.max_rows", None, "display.max_columns", None):
    display(df)

,Opcode,Mnemonic,Gas Constant,Gas Dynamic,Inputs,Output,Mem / Storage,Notes,Back
0,00,STOP,0,NaN,NaN,NaN,NaN,halt execution,"<h2>\n STOP (00)\n</h2>\n<dl style=""text-align..."
1,01,ADD,3,NaN,"a, b",a + b,NaN,(u)int256 addition modulo 2**256,"<h2>\n ADD (01)\n</h2>\n<dl style=""text-align:..."
2,02,MUL,5,NaN,"a, b",a * b,NaN,(u)int256 multiplication modulo 2**256,"<h2>\n MUL (02)\n</h2>\n<dl style=""text-align:..."
3,03,SUB,3,NaN,"a, b",a - b,NaN,(u)int256 addition modulo 2**256,"<h2>\n SUB (03)\n</h2>\n<dl style=""text-align:..."
4,04,DIV,5,NaN,"a, b",a // b,NaN,uint256 division,"<h2>\n DIV (04)\n</h2>\n<dl style=""text-align:..."
5,05,SDIV,5,NaN,"a, b",a // b,NaN,int256 division,"<h2>\n SDIV (05)\n</h2>\n<dl style=""text-align..."
6,06,MOD,5,NaN,"a, b",a % b,NaN,uint256 modulus,"<h2>\n MOD (06)\n</h2>\n<dl style=""text-align:..."
7,07,SMOD,5,NaN,"a, b",a % b,NaN,int256 modulus,"<h2>\n SMOD (07)\n</h2>\n<dl style=""text-align..."
8,08,ADDMOD,8,NaN,"a, b, N",(a + b) % N,NaN,(u)int256 addition modulo N,"<h2>\n ADDMOD (08)\n</h2>\n<dl style=""text-ali..."
9,09,MULMOD,8,NaN,"a, b, N",(a * b) % N,NaN,(u)int256 multiplication modulo N,"<h2>\n MULMOD (09)\n</h2>\n<dl style=""text-ali..."
10,0A,EXP,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"a, b",a ** b,NaN,uint256 exponentiation modulo 2**256,"<h2>\n EXP (0A)\n</h2>\n<dl style=""text-align:..."
11,0B,SIGNEXTEND,5,NaN,"b, x","SIGNEXTEND(x, b)",NaN,sign extend x from (b+1) bytes to 32 bytes,"<h2>\n SIGNEXTEND (0B)\n</h2>\n<dl style=""text..."
12,0C-0F,invalid,NaN,NaN,NaN,NaN,NaN,NaN,"<h2>\n invalid (0C-0F)\n</h2>\n<dl style=""text..."
13,10,LT,3,NaN,"a, b",a < b,NaN,uint256 less-than,"<h2>\n LT (10)\n</h2>\n<dl style=""text-align: ..."
14,11,GT,3,NaN,"a, b",a > b,NaN,uint256 greater-than,"<h2>\n GT (11)\n</h2>\n<dl style=""text-align: ..."
15,12,SLT,3,NaN,"a, b",a < b,NaN,int256 less-than,"<h2>\n SLT (12)\n</h2>\n<dl style=""text-align:..."
16,13,SGT,3,NaN,"a, b",a > b,NaN,int256 greater-than,"<h2>\n SGT (13)\n</h2>\n<dl style=""text-align:..."
17,14,EQ,3,NaN,"a, b",a == b,NaN,(u)int256 equality,"<h2>\n EQ (14)\n</h2>\n<dl style=""text-align: ..."
18,15,ISZERO,3,NaN,a,a == 0,NaN,(u)int256 iszero,"<h2>\n ISZERO (15)\n</h2>\n<dl style=""text-ali..."
19,16,AND,3,NaN,"a, b",a && b,NaN,bitwise AND,"<h2>\n AND (16)\n</h2>\n<dl style=""text-align:..."
20,17,OR,3,NaN,"a, b",a \|\| b,NaN,bitwise OR,"<h2>\n OR (17)\n</h2>\n<dl style=""text-align: ..."
21,18,XOR,3,NaN,"a, b",a ^ b,NaN,bitwise XOR,"<h2>\n XOR (18)\n</h2>\n<dl style=""text-align:..."
22,19,NOT,3,NaN,a,~a,NaN,bitwise NOT,"<h2>\n NOT (19)\n</h2>\n<dl style=""text-align:..."
23,1A,BYTE,3,NaN,"i, x",(x >> (248 - i * 8)) && 0xFF,NaN,"ith byte of (u)int256 x, from the left","<h2>\n BYTE (1A)\n</h2>\n<dl style=""text-align..."
24,1B,SHL,3,NaN,"shift, val",val << shift,NaN,shift left,"<h2>\n SHL (1B)\n</h2>\n<dl style=""text-align:..."
25,1C,SHR,3,NaN,"shift, val",val >> shift,NaN,logical shift right,"<h2>\n SHR (1C)\n</h2>\n<dl style=""text-align:..."
26,1D,SAR,3,NaN,"shift, val",val >> shift,NaN,arithmetic shift right,"<h2>\n SAR (1D)\n</h2>\n<dl style=""text-align:..."
27,1E-1F,invalid,NaN,NaN,NaN,NaN,NaN,NaN,"<h2>\n invalid (1E-1F)\n</h2>\n<dl style=""text..."
28,20,KECCAK256,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len",keccak256(mem[ost:ost+len-1]),NaN,keccak256,"<h2>\n KECCAK256 (20)\n</h2>\n<dl style=""text-..."
29,21-2F,invalid,NaN,NaN,NaN,NaN,NaN,NaN,"<h2>\n invalid (21-2F)\n</h2>\n<dl style=""text..."
30,30,ADDRESS,2,NaN,.,address(this),NaN,address of executing contract,"<h2>\n ADDRESS (30)\n</h2>\n<dl style=""text-al..."
31,31,BALANCE,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,addr,addr.balance,NaN,"balance, in wei","<h2>\n BALANCE (31)\n</h2>\n<dl style=""text-al..."
32,32,ORIGIN,2,NaN,.,tx.origin,NaN,address that originated the tx,"<h2>\n ORIGIN (32)\n</h2>\n<dl style=""text-ali..."
33,33,CALLER,2,NaN,.,msg.sender,NaN,address of msg sender,"<h2>\n CALLER (33)\n</h2>\n<dl style=""text-ali..."
34,34,CALLVALUE,2,NaN,.,msg.value,NaN,"msg value, in wei","<h2>\n CALLVALUE (34)\n</h2>\n<dl style=""text-..."
35,35,CALLDATALOAD,3,NaN,idx,msg.data[idx:idx+32],NaN,read word from msg data at index idx,"<h2>\n CALLDATALOAD (35)\n</h2>\n<dl style=""te..."
36,36,CALLDATASIZE,2,NaN,.,len(msg.data),NaN,"length of msg data, in bytes","<h2>\n CALLDATASIZE (36)\n</h2>\n<dl style=""te..."
37,37,CALLDATACOPY,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"dstOst, ost, len",.,mem[dstOst:dstOst+len-1] := msg.data[ost:ost+l...,copy msg data,"<h2>\n CALLDATACOPY (37)\n</h2>\n<dl style=""te..."
38,38,CODESIZE,2,NaN,.,len(this.code),NaN,"length of executing contract's code, in bytes","<h2>\n CODESIZE (38)\n</h2>\n<dl style=""text-a..."
39,39,CODECOPY,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"dstOst, ost, len",.,mem[dstOst:dstOst+len-1] := this.code[ost:ost+...,copy executing contract's bytecode,"<h2>\n CODECOPY (39)\n</h2>\n<dl style=""text-a..."
40,3A,GASPRICE,2,NaN,.,tx.gasprice,NaN,"gas price of tx, in wei per unit gas **","<h2>\n GASPRICE (3A)\n</h2>\n<dl style=""text-a..."
41,3B,EXTCODESIZE,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,addr,len(addr.code),NaN,"size of code at addr, in bytes","<h2>\n EXTCODESIZE (3B)\n</h2>\n<dl style=""tex..."
42,3C,EXTCODECOPY,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"addr, dstOst, ost, len",.,mem[dstOst:dstOst+len-1] := addr.code[ost:ost+...,copy code from addr,"<h2>\n EXTCODECOPY (3C)\n</h2>\n<dl style=""tex..."
43,3D,RETURNDATASIZE,2,NaN,.,size,NaN,"size of returned data from last external call,...","<h2>\n RETURNDATASIZE (3D)\n</h2>\n<dl style=""..."
44,3E,RETURNDATACOPY,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"dstOst, ost, len",.,mem[dstOst:dstOst+len-1] := returndata[ost:ost...,copy returned data from last external call,"<h2>\n RETURNDATACOPY (3E)\n</h2>\n<dl style=""..."
45,3F,EXTCODEHASH,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,addr,hash,NaN,hash = addr.exists ? keccak256(addr.code) : 0,"<h2>\n EXTCODEHASH (3F)\n</h2>\n<dl style=""tex..."
46,40,BLOCKHASH,20,NaN,blockNum,blockHash(blockNum),NaN,NaN,"<h2>\n BLOCKHASH (40)\n</h2>\n<dl style=""text-..."
47,41,COINBASE,2,NaN,.,block.coinbase,NaN,address of miner of current block,"<h2>\n COINBASE (41)\n</h2>\n<dl style=""text-a..."
48,42,TIMESTAMP,2,NaN,.,block.timestamp,NaN,timestamp of current block,"<h2>\n TIMESTAMP (42)\n</h2>\n<dl style=""text-..."
49,43,NUMBER,2,NaN,.,block.number,NaN,number of current block,"<h2>\n NUMBER (43)\n</h2>\n<dl style=""text-ali..."
50,44,PREVRANDAO,2,NaN,.,randomness beacon,NaN,randomness beacon,"<h2>\n PREVRANDAO (44)\n</h2>\n<dl style=""text..."
51,45,GASLIMIT,2,NaN,.,block.gaslimit,NaN,gas limit of current block,"<h2>\n GASLIMIT (45)\n</h2>\n<dl style=""text-a..."
52,46,CHAINID,2,NaN,.,chain_id,NaN,push current chain id onto stack,"<h2>\n CHAINID (46)\n</h2>\n<dl style=""text-al..."
53,47,SELFBALANCE,5,NaN,.,address(this).balance,NaN,"balance of executing contract, in wei","<h2>\n SELFBALANCE (47)\n</h2>\n<dl style=""tex..."
54,48,BASEFEE,2,NaN,.,block.basefee,NaN,base fee of current block,"<h2>\n BASEFEE (48)\n</h2>\n<dl style=""text-al..."
55,49,BLOBHASH,3,NaN,idx,tx.blob_versioned_hashes[idx],NaN,EIP-4844,"<h2>\n BLOBHASH (49)\n</h2>\n<dl style=""text-a..."
56,4A,BLOBBASEFEE,2,NaN,.,block.blobbasefee,NaN,blob base fee of current block (EIP-7516),"<h2>\n BLOBBASEFEE (4A)\n</h2>\n<dl style=""tex..."
57,4B-4F,invalid,NaN,NaN,NaN,NaN,NaN,NaN,"<h2>\n invalid (4B-4F)\n</h2>\n<dl style=""text..."
58,50,POP,2,NaN,_anon,.,NaN,remove item from top of stack and discard it,"<h2>\n POP (50)\n</h2>\n<dl style=""text-align:..."
59,51,MLOAD,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,ost,mem[ost:ost+32],NaN,read word from memory at offset ost,"<h2>\n MLOAD (51)\n</h2>\n<dl style=""text-alig..."
60,52,MSTORE,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, val",.,mem[ost:ost+32] := val,write a word to memory,"<h2>\n MSTORE (52)\n</h2>\n<dl style=""text-ali..."
61,53,MSTORE8,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, val",.,mem[ost] := val && 0xFF,write a single byte to memory,"<h2>\n MSTORE8 (53)\n</h2>\n<dl style=""text-al..."
62,54,SLOAD,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,key,storage[key],NaN,read word from storage,"<h2>\n SLOAD (54)\n</h2>\n<dl style=""text-alig..."
63,55,SSTORE,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"key, val",.,storage[key] := val,write word to storage,"<h2>\n SSTORE (55)\n</h2>\n<dl style=""text-ali..."
64,56,JUMP,8,NaN,dst,.,NaN,$pc := dst mark that pc is only assigned if ds...,"<h2>\n JUMP (56)\n</h2>\n<dl style=""text-align..."
65,57,JUMPI,10,NaN,"dst, condition",.,NaN,$pc := condition ? dst : $pc + 1,"<h2>\n JUMPI (57)\n</h2>\n<dl style=""text-alig..."
66,58,PC,2,NaN,.,$pc,NaN,program counter,"<h2>\n PC (58)\n</h2>\n<dl style=""text-align: ..."
67,59,MSIZE,2,NaN,.,len(mem),NaN,"size of memory in current execution context, i...","<h2>\n MSIZE (59)\n</h2>\n<dl style=""text-alig..."
68,5A,GAS,2,NaN,.,gasRemaining,NaN,NaN,"<h2>\n GAS (5A)\n</h2>\n<dl style=""text-align:..."
69,5B,JUMPDEST,1,NaN,NaN,NaN,mark valid jump destination,a valid jump destination for example a jump de...,"<h2>\n JUMPDEST (5B)\n</h2>\n<dl style=""text-a..."
70,5C,TLOAD,100,NaN,key,tstorage[key],NaN,read word from transient storage (EIP-1153),"<h2>\n TLOAD (5C)\n</h2>\n<dl style=""text-alig..."
71,5D,TSTORE,100,NaN,"key, val",.,tstorage[key] := val,write word to transient storage (EIP-1153),"<h2>\n TSTORE (5D)\n</h2>\n<dl style=""text-ali..."
72,5E,MCOPY,3 + 3 * words +,https://github.com/wolflo/evm-opcodes/blob/mai...,"dstOst, ost, len",.,mem[dstOst] := mem[ost:ost+len],copy memory from one area to another (EIP-5656),"<h2>\n MCOPY (5E)\n</h2>\n<dl style=""text-alig..."
73,5F,PUSH0,2,NaN,.,uint8,NaN,push the constant value 0 onto stack,"<h2>\n PUSH0 (5F)\n</h2>\n<dl style=""text-alig..."
74,60,PUSH1,3,NaN,.,uint8,NaN,push 1-byte value onto stack,"<h2>\n PUSH1 (60)\n</h2>\n<dl style=""text-alig..."
75,61,PUSH2,3,NaN,.,uint16,NaN,push 2-byte value onto stack,"<h2>\n PUSH2 (61)\n</h2>\n<dl style=""text-alig..."
76,62,PUSH3,3,NaN,.,uint24,NaN,push 3-byte value onto stack,"<h2>\n PUSH3 (62)\n</h2>\n<dl style=""text-alig..."
77,63,PUSH4,3,NaN,.,uint32,NaN,push 4-byte value onto stack,"<h2>\n PUSH4 (63)\n</h2>\n<dl style=""text-alig..."
78,64,PUSH5,3,NaN,.,uint40,NaN,push 5-byte value onto stack,"<h2>\n PUSH5 (64)\n</h2>\n<dl style=""text-alig..."
79,65,PUSH6,3,NaN,.,uint48,NaN,push 6-byte value onto stack,"<h2>\n PUSH6 (65)\n</h2>\n<dl style=""text-alig..."
80,66,PUSH7,3,NaN,.,uint56,NaN,push 7-byte value onto stack,"<h2>\n PUSH7 (66)\n</h2>\n<dl style=""text-alig..."
81,67,PUSH8,3,NaN,.,uint64,NaN,push 8-byte value onto stack,"<h2>\n PUSH8 (67)\n</h2>\n<dl style=""text-alig..."
82,68,PUSH9,3,NaN,.,uint72,NaN,push 9-byte value onto stack,"<h2>\n PUSH9 (68)\n</h2>\n<dl style=""text-alig..."
83,69,PUSH10,3,NaN,.,uint80,NaN,push 10-byte value onto stack,"<h2>\n PUSH10 (69)\n</h2>\n<dl style=""text-ali..."
84,6A,PUSH11,3,NaN,.,uint88,NaN,push 11-byte value onto stack,"<h2>\n PUSH11 (6A)\n</h2>\n<dl style=""text-ali..."
85,6B,PUSH12,3,NaN,.,uint96,NaN,push 12-byte value onto stack,"<h2>\n PUSH12 (6B)\n</h2>\n<dl style=""text-ali..."
86,6C,PUSH13,3,NaN,.,uint104,NaN,push 13-byte value onto stack,"<h2>\n PUSH13 (6C)\n</h2>\n<dl style=""text-ali..."
87,6D,PUSH14,3,NaN,.,uint112,NaN,push 14-byte value onto stack,"<h2>\n PUSH14 (6D)\n</h2>\n<dl style=""text-ali..."
88,6E,PUSH15,3,NaN,.,uint120,NaN,push 15-byte value onto stack,"<h2>\n PUSH15 (6E)\n</h2>\n<dl style=""text-ali..."
89,6F,PUSH16,3,NaN,.,uint128,NaN,push 16-byte value onto stack,"<h2>\n PUSH16 (6F)\n</h2>\n<dl style=""text-ali..."
90,70,PUSH17,3,NaN,.,uint136,NaN,push 17-byte value onto stack,"<h2>\n PUSH17 (70)\n</h2>\n<dl style=""text-ali..."
91,71,PUSH18,3,NaN,.,uint144,NaN,push 18-byte value onto stack,"<h2>\n PUSH18 (71)\n</h2>\n<dl style=""text-ali..."
92,72,PUSH19,3,NaN,.,uint152,NaN,push 19-byte value onto stack,"<h2>\n PUSH19 (72)\n</h2>\n<dl style=""text-ali..."
93,73,PUSH20,3,NaN,.,uint160,NaN,push 20-byte value onto stack,"<h2>\n PUSH20 (73)\n</h2>\n<dl style=""text-ali..."
94,74,PUSH21,3,NaN,.,uint168,NaN,push 21-byte value onto stack,"<h2>\n PUSH21 (74)\n</h2>\n<dl style=""text-ali..."
95,75,PUSH22,3,NaN,.,uint176,NaN,push 22-byte value onto stack,"<h2>\n PUSH22 (75)\n</h2>\n<dl style=""text-ali..."
96,76,PUSH23,3,NaN,.,uint184,NaN,push 23-byte value onto stack,"<h2>\n PUSH23 (76)\n</h2>\n<dl style=""text-ali..."
97,77,PUSH24,3,NaN,.,uint192,NaN,push 24-byte value onto stack,"<h2>\n PUSH24 (77)\n</h2>\n<dl style=""text-ali..."
98,78,PUSH25,3,NaN,.,uint200,NaN,push 25-byte value onto stack,"<h2>\n PUSH25 (78)\n</h2>\n<dl style=""text-ali..."
99,79,PUSH26,3,NaN,.,uint208,NaN,push 26-byte value onto stack,"<h2>\n PUSH26 (79)\n</h2>\n<dl style=""text-ali..."
100,7A,PUSH27,3,NaN,.,uint216,NaN,push 27-byte value onto stack,"<h2>\n PUSH27 (7A)\n</h2>\n<dl style=""text-ali..."
101,7B,PUSH28,3,NaN,.,uint224,NaN,push 28-byte value onto stack,"<h2>\n PUSH28 (7B)\n</h2>\n<dl style=""text-ali..."
102,7C,PUSH29,3,NaN,.,uint232,NaN,push 29-byte value onto stack,"<h2>\n PUSH29 (7C)\n</h2>\n<dl style=""text-ali..."
103,7D,PUSH30,3,NaN,.,uint240,NaN,push 30-byte value onto stack,"<h2>\n PUSH30 (7D)\n</h2>\n<dl style=""text-ali..."
104,7E,PUSH31,3,NaN,.,uint248,NaN,push 31-byte value onto stack,"<h2>\n PUSH31 (7E)\n</h2>\n<dl style=""text-ali..."
105,7F,PUSH32,3,NaN,.,uint256,NaN,push 32-byte value onto stack,"<h2>\n PUSH32 (7F)\n</h2>\n<dl style=""text-ali..."
106,80,DUP1,3,NaN,a,"a, a",NaN,clone 1st value on stack,"<h2>\n DUP1 (80)\n</h2>\n<dl style=""text-align..."
107,81,DUP2,3,NaN,"_, a","a, _, a",NaN,clone 2nd value on stack,"<h2>\n DUP2 (81)\n</h2>\n<dl style=""text-align..."
108,82,DUP3,3,NaN,"_, _, a","a, _, _, a",NaN,clone 3rd value on stack,"<h2>\n DUP3 (82)\n</h2>\n<dl style=""text-align..."
109,83,DUP4,3,NaN,"_, _, _, a","a, _, _, _, a",NaN,clone 4th value on stack,"<h2>\n DUP4 (83)\n</h2>\n<dl style=""text-align..."
110,84,DUP5,3,NaN,"..., a","a, ..., a",NaN,clone 5th value on stack,"<h2>\n DUP5 (84)\n</h2>\n<dl style=""text-align..."
111,85,DUP6,3,NaN,"..., a","a, ..., a",NaN,clone 6th value on stack,"<h2>\n DUP6 (85)\n</h2>\n<dl style=""text-align..."
112,86,DUP7,3,NaN,"..., a","a, ..., a",NaN,clone 7th value on stack,"<h2>\n DUP7 (86)\n</h2>\n<dl style=""text-align..."
113,87,DUP8,3,NaN,"..., a","a, ..., a",NaN,clone 8th value on stack,"<h2>\n DUP8 (87)\n</h2>\n<dl style=""text-align..."
114,88,DUP9,3,NaN,"..., a","a, ..., a",NaN,clone 9th value on stack,"<h2>\n DUP9 (88)\n</h2>\n<dl style=""text-align..."
115,89,DUP10,3,NaN,"..., a","a, ..., a",NaN,clone 10th value on stack,"<h2>\n DUP10 (89)\n</h2>\n<dl style=""text-alig..."
116,8A,DUP11,3,NaN,"..., a","a, ..., a",NaN,clone 11th value on stack,"<h2>\n DUP11 (8A)\n</h2>\n<dl style=""text-alig..."
117,8B,DUP12,3,NaN,"..., a","a, ..., a",NaN,clone 12th value on stack,"<h2>\n DUP12 (8B)\n</h2>\n<dl style=""text-alig..."
118,8C,DUP13,3,NaN,"..., a","a, ..., a",NaN,clone 13th value on stack,"<h2>\n DUP13 (8C)\n</h2>\n<dl style=""text-alig..."
119,8D,DUP14,3,NaN,"..., a","a, ..., a",NaN,clone 14th value on stack,"<h2>\n DUP14 (8D)\n</h2>\n<dl style=""text-alig..."
120,8E,DUP15,3,NaN,"..., a","a, ..., a",NaN,clone 15th value on stack,"<h2>\n DUP15 (8E)\n</h2>\n<dl style=""text-alig..."
121,8F,DUP16,3,NaN,"..., a","a, ..., a",NaN,clone 16th value on stack,"<h2>\n DUP16 (8F)\n</h2>\n<dl style=""text-alig..."
122,90,SWAP1,3,NaN,"a, b","b, a",NaN,NaN,"<h2>\n SWAP1 (90)\n</h2>\n<dl style=""text-alig..."
123,91,SWAP2,3,NaN,"a, _, b","b, _, a",NaN,NaN,"<h2>\n SWAP2 (91)\n</h2>\n<dl style=""text-alig..."
124,92,SWAP3,3,NaN,"a, _, _, b","b, _, _, a",NaN,NaN,"<h2>\n SWAP3 (92)\n</h2>\n<dl style=""text-alig..."
125,93,SWAP4,3,NaN,"a, _, _, _, b","b, _, _, _, a",NaN,NaN,"<h2>\n SWAP4 (93)\n</h2>\n<dl style=""text-alig..."
126,94,SWAP5,3,NaN,"a, ..., b","b, ..., a",NaN,NaN,"<h2>\n SWAP5 (94)\n</h2>\n<dl style=""text-alig..."
127,95,SWAP6,3,NaN,"a, ..., b","b, ..., a",NaN,NaN,"<h2>\n SWAP6 (95)\n</h2>\n<dl style=""text-alig..."
128,96,SWAP7,3,NaN,"a, ..., b","b, ..., a",NaN,NaN,"<h2>\n SWAP7 (96)\n</h2>\n<dl style=""text-alig..."
129,97,SWAP8,3,NaN,"a, ..., b","b, ..., a",NaN,NaN,"<h2>\n SWAP8 (97)\n</h2>\n<dl style=""text-alig..."
130,98,SWAP9,3,NaN,"a, ..., b","b, ..., a",NaN,NaN,"<h2>\n SWAP9 (98)\n</h2>\n<dl style=""text-alig..."
131,99,SWAP10,3,NaN,"a, ..., b","b, ..., a",NaN,NaN,"<h2>\n SWAP10 (99)\n</h2>\n<dl style=""text-ali..."
132,9A,SWAP11,3,NaN,"a, ..., b","b, ..., a",NaN,NaN,"<h2>\n SWAP11 (9A)\n</h2>\n<dl style=""text-ali..."
133,9B,SWAP12,3,NaN,"a, ..., b","b, ..., a",NaN,NaN,"<h2>\n SWAP12 (9B)\n</h2>\n<dl style=""text-ali..."
134,9C,SWAP13,3,NaN,"a, ..., b","b, ..., a",NaN,NaN,"<h2>\n SWAP13 (9C)\n</h2>\n<dl style=""text-ali..."
135,9D,SWAP14,3,NaN,"a, ..., b","b, ..., a",NaN,NaN,"<h2>\n SWAP14 (9D)\n</h2>\n<dl style=""text-ali..."
136,9E,SWAP15,3,NaN,"a, ..., b","b, ..., a",NaN,NaN,"<h2>\n SWAP15 (9E)\n</h2>\n<dl style=""text-ali..."
137,9F,SWAP16,3,NaN,"a, ..., b","b, ..., a",NaN,NaN,"<h2>\n SWAP16 (9F)\n</h2>\n<dl style=""text-ali..."
138,A0,LOG0,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len",.,NaN,LOG0(memory[ost:ost+len-1]),"<h2>\n LOG0 (A0)\n</h2>\n<dl style=""text-align..."
139,A1,LOG1,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len, topic0",.,NaN,"LOG1(memory[ost:ost+len-1], topic0)","<h2>\n LOG1 (A1)\n</h2>\n<dl style=""text-align..."
140,A2,LOG2,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len, topic0, topic1",.,NaN,"LOG2(memory[ost:ost+len-1], topic0, topic1)","<h2>\n LOG2 (A2)\n</h2>\n<dl style=""text-align..."
141,A3,LOG3,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len, topic0, topic1, topic2",.,NaN,"LOG3(memory[ost:ost+len-1], topic0, topic1, to...","<h2>\n LOG3 (A3)\n</h2>\n<dl style=""text-align..."
142,A4,LOG4,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len, topic0, topic1, topic2, topic3",.,NaN,"LOG4(memory[ost:ost+len-1], topic0, topic1, to...","<h2>\n LOG4 (A4)\n</h2>\n<dl style=""text-align..."
143,A5-EF,invalid,NaN,NaN,NaN,NaN,NaN,NaN,"<h2>\n invalid (A5-EF)\n</h2>\n<dl style=""text..."
144,F0,CREATE,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"val, ost, len",addr,NaN,"addr = keccak256(rlp([address(this), this.nonc...","<h2>\n CREATE (F0)\n</h2>\n<dl style=""text-ali..."
145,F1,CALL,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"gas, addr, val, argOst, argLen, retOst, retLen",success,mem[retOst:retOst+retLen-1] := returndata,NaN,"<h2>\n CALL (F1)\n</h2>\n<dl style=""text-align..."
146,F2,CALLCODE,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"gas, addr, val, argOst, argLen, retOst, retLen",success,mem[retOst:retOst+retLen-1] = returndata,"same as DELEGATECALL, but does not propagate o...","<h2>\n CALLCODE (F2)\n</h2>\n<dl style=""text-a..."
147,F3,RETURN,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"ost, len",.,NaN,return mem[ost:ost+len-1],"<h2>\n RETURN (F3)\n</h2>\n<dl style=""text-ali..."
148,F4,DELEGATECALL,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"gas, addr, argOst, argLen, retOst, retLen",success,mem[retOst:retOst+retLen-1] := returndata,NaN,"<h2>\n DELEGATECALL (F4)\n</h2>\n<dl style=""te..."
149,F5,CREATE2,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"val, ost, len, salt",addr,NaN,addr = keccak256(0xff ++ address(this) ++ salt...,"<h2>\n CREATE2 (F5)\n</h2>\n<dl style=""text-al..."
150,F6-F9,invalid,NaN,NaN,NaN,NaN,NaN,NaN,"<h2>\n invalid (F6-F9)\n</h2>\n<dl style=""text..."
151,FA,STATICCALL,NaN,https://github.com/wolflo/evm-opcodes/blob/mai...,"gas, addr, argOst, argLen, retOst, retLen",success,mem[retOst:retOst+retLen-1] := returndata,NaN,"<h2>\n STATICCALL (FA)\n</h2>\n<dl style=""text..."

In [5]:
def create_front(row, title):
    s = BeautifulSoup("", "html.parser")
    kind = s.new_tag("p")
    kind.append(NavigableString(title))
    s.append(kind)
    question = s.new_tag("p")
    question.append(NavigableString(str(row["Front"])))
    s.append(question)
    return s.prettify()

In [6]:
def create_set(column):
    mnemonic = df.copy()
    mnemonic.rename(columns={column: "Front"}, inplace=True)
    mnemonic["Front"] = mnemonic.apply(create_front, title=column, axis=1)
    mnemonic.drop(
        columns=[c for c in mnemonic.columns if c not in ["Back", "Front"]],
        inplace=True,
    )
    mnemonic.drop_duplicates(subset=["Front"], inplace=True)
    mnemonic.dropna(subset=["Front"], inplace=True)
    mnemonic["Tags"] = column
    return mnemonic

In [7]:
concat = pd.concat(
    [
        create_set("Opcode"),
        create_set("Mnemonic"),
        create_set("Output"),
        create_set("Notes"),
    ],
    ignore_index=True,
)
concat

,Front,Back,Tags
0,<p>\n Opcode\n</p>\n<p>\n 00\n</p>\n,"<h2>\n STOP (00)\n</h2>\n<dl style=""text-align...",Opcode
1,<p>\n Opcode\n</p>\n<p>\n 01\n</p>\n,"<h2>\n ADD (01)\n</h2>\n<dl style=""text-align:...",Opcode
2,<p>\n Opcode\n</p>\n<p>\n 02\n</p>\n,"<h2>\n MUL (02)\n</h2>\n<dl style=""text-align:...",Opcode
3,<p>\n Opcode\n</p>\n<p>\n 03\n</p>\n,"<h2>\n SUB (03)\n</h2>\n<dl style=""text-align:...",Opcode
4,<p>\n Opcode\n</p>\n<p>\n 04\n</p>\n,"<h2>\n DIV (04)\n</h2>\n<dl style=""text-align:...",Opcode
...,...,...,...
525,<p>\n Notes\n</p>\n<p>\n return mem[ost:ost+le...,"<h2>\n RETURN (F3)\n</h2>\n<dl style=""text-ali...",Notes
526,<p>\n Notes\n</p>\n<p>\n addr = keccak256(0xff...,"<h2>\n CREATE2 (F5)\n</h2>\n<dl style=""text-al...",Notes
527,<p>\n Notes\n</p>\n<p>\n revert(mem[ost:ost+le...,"<h2>\n REVERT (FD)\n</h2>\n<dl style=""text-ali...",Notes
528,<p>\n Notes\n</p>\n<p>\n designated invalid op...,"<h2>\n INVALID (FE)\n</h2>\n<dl style=""text-al...",Notes
529,<p>\n Notes\n</p>\n<p>\n sends all ETH to addr...,"<h2>\n SELFDESTRUCT (FF)\n</h2>\n<dl style=""te...",Notes

In [8]:
concat.to_csv(
    target_abspath, sep="|", index=False, header=False, encoding="utf-8"
)